//! Cross-language canonical-JSON parity gate.
//!
//! The e2e harness runs on Node and re-implements Arkret canonical JSON in
//! TypeScript (`canonicalJson` in `e2e/helpers/soland-api.ts`) because it cannot
//! call the Rust SDK directly. The authoritative implementation is the SDK's
//! `arkret_canonical` (RFC 8785 JCS, integer-only number profile), and the
//! final signatures e2e produces are verified by soland using that SDK — so any
//! byte-level drift between the TS reimplementation and the SDK is a silent
//! signature false-negative/false-positive vector.
//!
//! This gate (Rust side) and `e2e/tests/conformance/canonical-cross-lang.spec.ts`
//! (TS side) both read the same golden vectors in
//! `e2e/fixtures/canonical-cross-check.json` and assert their respective
//! implementation reproduces the golden `canonical` byte-for-byte. The golden
//! column is generated by the SDK; if the SDK profile changes, regenerate it and
//! both sides re-pin in lock-step. If only one implementation drifts, only that
//! side fails — which localises the regression.

use std::path::PathBuf;

use anyhow::{Context, Result, bail};
use serde::Deserialize;
use serde_json::Value;

#[derive(Debug, Deserialize)]
struct CrossCheckDoc {
    vectors: Vec<CrossCheckVector>,
}

#[derive(Debug, Deserialize)]
struct CrossCheckVector {
    value: Value,
    canonical: String,
}

fn cross_check_fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("e2e")
        .join("fixtures")
        .join("canonical-cross-check.json")
}

/// Assert the SDK canonicaliser reproduces every golden vector exactly. Mirrors
/// `e2e/tests/conformance/canonical-cross-lang.spec.ts` against the TS port.
pub fn run_canonical_cross_lang_suite() -> Result<()> {
    let path = cross_check_fixture_path();
    let raw = std::fs::read_to_string(&path)
        .with_context(|| format!("read canonical cross-check fixture {}", path.display()))?;
    let doc: CrossCheckDoc = serde_json::from_str(&raw)
        .with_context(|| format!("parse canonical cross-check fixture {}", path.display()))?;

    if doc.vectors.is_empty() {
        bail!("canonical cross-check fixture has no vectors");
    }

    for (idx, vector) in doc.vectors.iter().enumerate() {
        let produced = arkret_canonical::canonical_json_string(&vector.value)
            .with_context(|| format!("vector[{idx}]: SDK canonicalization failed"))?;
        if produced != vector.canonical {
            bail!(
                "vector[{idx}]: SDK canonical drift from golden\n  golden:   {}\n  produced: {}",
                vector.canonical,
                produced
            );
        }
    }

    Ok(())
}
