//! 05-2 — Cross-language golden gate for the device-lifecycle §5.1 / §5.2
//! canonical signing inputs.
//!
//! The e2e harness runs on Node and byte-mirrors the SDK's cross-signing /
//! device-trust canonical signing-input construction in TypeScript
//! (`e2e/helpers/cross-signing-harness.ts`) because it cannot call the Rust SDK
//! directly. The authoritative construction is
//! `arkret_core::CrossSigningPublish::{self,user}_signing_binding_input`
//! (`ak.cross-signing-bind-v1`) and `arkret_crypto::DeviceTrustBinding::canonical_input`
//! (`ak.device-trust-bind-v1`); soland verifies the resulting signatures with
//! those exact bytes, so any drift between the TS mirror and the SDK is a silent
//! signature false-negative/false-positive vector.
//!
//! This gate (Rust side) and
//! `e2e/tests/conformance/cross-signing-binding-golden.spec.ts` (TS side) read
//! the same golden vectors in `e2e/fixtures/cross-signing-binding-golden.json`
//! and assert their respective implementation reproduces the golden base64
//! byte-for-byte. The golden columns are generated by the SDK (via the
//! `cotest-wire` bin); if the SDK prefix / body field-set / canonical-JSON
//! encoding changes, regenerate both columns in lock-step. If only one
//! implementation drifts, only that side fails — which localises the regression.

use std::path::PathBuf;

use anyhow::{Context, Result, bail};
use arkret_core::{CrossSigningPublish, DeviceId, Did};
use arkret_crypto::DeviceTrustBinding;
use base64::Engine as _;
use serde::Deserialize;
use serde_json::Value;

#[derive(Debug, Deserialize)]
struct GoldenDoc {
    cross_signing_vectors: Vec<CrossSigningVector>,
    device_trust_vectors: Vec<DeviceTrustVector>,
}

#[derive(Debug, Deserialize)]
struct CrossSigningVector {
    name: String,
    publish_payload: Value,
    expected_self_signing_input_b64: String,
    expected_user_signing_input_b64: String,
}

#[derive(Debug, Deserialize)]
struct DeviceTrustVector {
    name: String,
    input: DeviceTrustInput,
    expected_input_b64: String,
}

#[derive(Debug, Deserialize)]
struct DeviceTrustInput {
    principal_id: String,
    device_id: String,
    device_public_key: String,
    hpke_key: String,
    algorithms: Vec<String>,
    ssk_generation: u64,
}

fn golden_fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("e2e")
        .join("fixtures")
        .join("cross-signing-binding-golden.json")
}

/// Assert the SDK reproduces every golden cross-signing / device-trust canonical
/// signing input exactly. Mirrors
/// `e2e/tests/conformance/cross-signing-binding-golden.spec.ts` against the TS
/// byte-mirror.
pub fn run_cross_signing_binding_golden_suite() -> Result<()> {
    let path = golden_fixture_path();
    let raw = std::fs::read_to_string(&path).with_context(|| {
        format!(
            "read cross-signing binding golden fixture {}",
            path.display()
        )
    })?;
    let doc: GoldenDoc = serde_json::from_str(&raw).with_context(|| {
        format!(
            "parse cross-signing binding golden fixture {}",
            path.display()
        )
    })?;

    if doc.cross_signing_vectors.is_empty() {
        bail!("cross-signing binding golden fixture has no cross_signing_vectors");
    }
    if doc.device_trust_vectors.is_empty() {
        bail!("cross-signing binding golden fixture has no device_trust_vectors");
    }

    let b64 = base64::engine::general_purpose::STANDARD;

    for vector in &doc.cross_signing_vectors {
        let content: CrossSigningPublish = serde_json::from_value(vector.publish_payload.clone())
            .with_context(|| {
            format!(
                "vector {}: parse publish_payload into SDK type",
                vector.name
            )
        })?;
        let self_signing =
            b64.encode(content.self_signing_binding_input().map_err(|err| {
                anyhow::anyhow!("vector {}: self_signing input: {err}", vector.name)
            })?);
        let user_signing =
            b64.encode(content.user_signing_binding_input().map_err(|err| {
                anyhow::anyhow!("vector {}: user_signing input: {err}", vector.name)
            })?);
        if self_signing != vector.expected_self_signing_input_b64 {
            bail!(
                "vector {}: SDK self_signing input drift from golden\n  golden:   {}\n  produced: {}",
                vector.name,
                vector.expected_self_signing_input_b64,
                self_signing
            );
        }
        if user_signing != vector.expected_user_signing_input_b64 {
            bail!(
                "vector {}: SDK user_signing input drift from golden\n  golden:   {}\n  produced: {}",
                vector.name,
                vector.expected_user_signing_input_b64,
                user_signing
            );
        }
    }

    for vector in &doc.device_trust_vectors {
        let principal = Did::new(vector.input.principal_id.clone())
            .map_err(|err| anyhow::anyhow!("vector {}: principal DID: {err}", vector.name))?;
        let device_id = DeviceId::new(vector.input.device_id.clone())
            .map_err(|err| anyhow::anyhow!("vector {}: device id: {err}", vector.name))?;
        let produced = b64.encode(
            DeviceTrustBinding::canonical_input(
                &principal,
                &device_id,
                &vector.input.device_public_key,
                &vector.input.hpke_key,
                &vector.input.algorithms,
                vector.input.ssk_generation,
            )
            .map_err(|err| anyhow::anyhow!("vector {}: device-trust input: {err}", vector.name))?,
        );
        if produced != vector.expected_input_b64 {
            bail!(
                "vector {}: SDK device-trust input drift from golden\n  golden:   {}\n  produced: {}",
                vector.name,
                vector.expected_input_b64,
                produced
            );
        }
    }

    Ok(())
}
