//! Executable semantics for `ak.vector.keypackage.recipient_claim_read.v1`
//! (`device-lifecycle.md` §9 `claims/query` and §9.2.4,
//! `encryption-and-audit.md` §2.6.1, decision 0119).
//!
//! The Station below is the claim destination. It owns only what the SDK
//! cannot decide: the claim ledger holding each claim request's first
//! serialized `keypackages_claim_outcome`, its query retention, and the
//! authenticated endpoint of each reading session. The claims themselves are
//! real: bob's and the Agent's KeyPackages are generated by the SDK MLS
//! identities, the receipt is signed over the SDK's registered transcript
//! with the Station's Ed25519 service key, and `claims_digest` is the SDK's.
//! The recipient side is real too: bob reads the claim, lets the SDK
//! recompute `claims_digest`, verifies the receipt signature, runs Garth's
//! `verify_welcome_claim` against alice's accepted inline-Add Commit, and only
//! then joins the RFC 9420 group from the Welcome.

use std::collections::BTreeMap;

use anyhow::{Context as _, Result, anyhow, bail, ensure};
use arkret::{ArkretMlsGroup, ArkretMlsIdentity, ArkretMlsSigner, MlsGovernanceBindingPayload};
use arkret_canonical::DigestSuite;
use arkret_models_crypto::{
    KeyOperationSignature, KeyPackageClaimRecord, KeyPackagesClaimOutcome, MlsCommitPayload,
    MlsKeyPackageRecord, PeerKeyPackageClaimPurpose, PeerKeyPackageClaimReceipt,
    PeerKeyPackagesClaimUnsignedRequest, peer_keypackage_claim_receipt_signing_bytes,
};
use arkret_wire::{
    AccountId, ActorId, Base64UrlString, CommittedEventFullView, DetachedSignatureAlgorithm,
    DetachedSignatureContext, DeviceId, DidCoreId, DidUrl, Event, EventId, EventKind, Hash,
    KeypackageClaimId, MlsWelcomeDelivery, MlsWelcomeDeliveryId, MlsWelcomeRecipientEndpoint,
    NonEmptyString, RealmCommit, RealmId, ScopeRef,
};
use chrono::{DateTime, Utc};
use ed25519_dalek::{Signer as _, SigningKey, Verifier as _};
use garth::mls::{LocalMlsEndpoint, verify_welcome_claim};
use serde_json::{Value, json};

use super::authority_forward_producer_device_evidence::sign;
use super::{
    CaseExecutionResult, SuiteExecutionResult, fixture_runner_entrypoint, load_fixture_value,
    required_field, required_str, scripted_cases, value_array, verify_decision_point_evidence,
};

pub const VECTOR_ID_KEYPACKAGE_RECIPIENT_CLAIM_READ: &str =
    "ak.vector.keypackage.recipient_claim_read.v1";
pub const KEYPACKAGE_RECIPIENT_CLAIM_READ_ENTRYPOINT: &str =
    "ak.suite.keypackage.recipient_claim_read.v1";

const FIXTURE: &str = "keypackage-recipient-claim-read-fixture.json";
const SUITE: &str = "keypackage_recipient_claim_read";

const EXECUTED_CASES: [(&str, &[&str]); 3] = [
    (
        "the_claimed_endpoint_reads_the_original_outcome",
        &[
            "device_reads_its_claim",
            "device_reads_its_claim_again",
            "agent_reads_under_its_current_authorization",
        ],
    ),
    (
        "every_other_reader_is_keypackage_unknown",
        &[
            "requester_reads_the_claim",
            "other_device_of_the_claimed_account",
            "unknown_claim_id",
            "agent_after_its_authorization_was_replaced",
            "claim_past_its_query_retention",
            "claimed_device_after_the_refusals",
        ],
    ),
    (
        "the_recipient_binds_the_claim_before_decrypting",
        &[
            "exact_claim_receipt_welcome_and_add_commit",
            "claim_read_refused",
            "claim_record_altered_after_the_receipt",
            "receipt_signed_by_another_key",
            "claimed_keypackage_not_added_by_the_commit",
            "endpoint_authorization_replaced",
        ],
    ),
];

const DECISION_POINTS: [&str; 4] = [
    "exact_endpoint_original_bytes",
    "uniform_keypackage_unknown",
    "read_only",
    "recipient_binds_before_decrypt",
];

const STATION_SEED: [u8; 32] = [0x61; 32];
const FOREIGN_SEED: [u8; 32] = [0x62; 32];
const ALICE_SEED: [u8; 32] = [0x63; 32];
const BOB_SEED: [u8; 32] = [0x64; 32];
const AGENT_SEED: [u8; 32] = [0x65; 32];
const BOB_AUTHORIZE: [u8; 32] = [0x71; 32];
const BOB_REPLACED_AUTHORIZE: [u8; 32] = [0x72; 32];
const AGENT_AUTHORIZE: [u8; 32] = [0x73; 32];
const AGENT_REPLACED_AUTHORIZE: [u8; 32] = [0x74; 32];
const GENESIS: [u8; 32] = [0x75; 32];
const AGENT_METHOD_FRAGMENT: &str = "agent-runtime-1";

pub fn run_keypackage_recipient_claim_read_suite() -> Result<SuiteExecutionResult> {
    let fixture = load_fixture_value(FIXTURE)?;
    verify_fixture_identity(&fixture)?;
    verify_decision_point_evidence(&fixture, &DECISION_POINTS)?;
    let world = World::load(required_field(&fixture, "world")?)?;
    let mut results = Vec::new();
    for (name, variants) in scripted_cases(&fixture, &EXECUTED_CASES)? {
        let mut station = Station::new(&world)?;
        let mut recipient = None;
        for variant in variants {
            let variant_name = required_str(variant, "name")?;
            let actual = match variant.get("operation").and_then(Value::as_str) {
                Some("receive_welcome") => {
                    let recipient = match recipient.as_mut() {
                        Some(recipient) => recipient,
                        None => recipient.insert(Recipient::new(&world, &station)?),
                    };
                    recipient.receive(&world, &station, variant)
                }
                _ => station.read_variant(&world, variant),
            }
            .with_context(|| format!("{name}/{variant_name}"))?;
            let expected = required_field(variant, "expected")?;
            ensure!(
                &actual == expected,
                "{name}/{variant_name} produced {actual}, fixture expects {expected}"
            );
        }
        results.push(CaseExecutionResult {
            case_id: name.to_owned(),
            assertions: variants.len(),
        });
    }
    Ok(SuiteExecutionResult {
        entrypoint: KEYPACKAGE_RECIPIENT_CLAIM_READ_ENTRYPOINT,
        fixture: FIXTURE,
        cases: results,
    })
}

pub fn run_keypackage_recipient_claim_read_vector() -> Result<()> {
    run_keypackage_recipient_claim_read_suite().map(drop)
}

fn verify_fixture_identity(fixture: &Value) -> Result<()> {
    ensure!(
        required_str(fixture, "suite")? == SUITE,
        "fixture suite drifted"
    );
    ensure!(
        fixture_runner_entrypoint(fixture)? == KEYPACKAGE_RECIPIENT_CLAIM_READ_ENTRYPOINT,
        "fixture entrypoint drifted"
    );
    ensure!(
        value_array(required_field(fixture, "covers_vectors")?, "covers_vectors")?
            .iter()
            .any(|id| id == VECTOR_ID_KEYPACKAGE_RECIPIENT_CLAIM_READ),
        "fixture no longer covers {VECTOR_ID_KEYPACKAGE_RECIPIENT_CLAIM_READ}"
    );
    Ok(())
}

fn event_id(seed: [u8; 32]) -> EventId {
    EventId::from_digest(DigestSuite::Sha256, seed)
}

fn timestamp(value: &Value) -> Result<DateTime<Utc>> {
    let text = value.as_str().context("timestamp must be a string")?;
    Ok(DateTime::parse_from_rfc3339(text)?.to_utc())
}

// ---------------------------------------------------------------------------
// World
// ---------------------------------------------------------------------------

/// One authenticated reading session: the endpoint the Station resolved it
/// to.
#[derive(Clone, Debug)]
enum Reader {
    Device {
        actor: ActorId,
        device_id: DeviceId,
    },
    Agent {
        agent_id: DidCoreId,
        verification_method: DidUrl,
        authorize_event_id: EventId,
    },
}

struct World {
    station_id: DidCoreId,
    station_method: DidUrl,
    realm_id: RealmId,
    scope: ScopeRef,
    alice: AccountId,
    alice_device: DeviceId,
    bob: AccountId,
    bob_device: DeviceId,
    agent: AccountId,
    agent_method: DidUrl,
    readers: BTreeMap<String, Reader>,
    claim_ids: BTreeMap<String, String>,
    claimed_at: DateTime<Utc>,
    claim_expires_at: DateTime<Utc>,
    retention_ends_at: DateTime<Utc>,
    clocks: BTreeMap<String, DateTime<Utc>>,
}

impl World {
    fn load(world: &Value) -> Result<Self> {
        let station_id = DidCoreId::new(required_str(world, "station_id")?)?;
        let host = station_id
            .as_str()
            .strip_prefix("ak:did_core:web:")
            .context("the fixture Station is a did:web Station")?
            .to_owned();
        let station_method =
            DidUrl::new(format!("did:web:{host}#service")).map_err(|error| anyhow!("{error}"))?;
        let realm_id = RealmId::new(required_str(world, "realm_id")?)?;
        let account = |name: &str| -> Result<AccountId> {
            Ok(AccountId::new(
                DidCoreId::new(format!("ak:did_core:web:{name}.example"))?,
                station_id.clone(),
            ))
        };
        let readers_value = required_field(world, "readers")?;
        let device = |reader: &str| -> Result<DeviceId> {
            Ok(DeviceId::new(required_str(
                &readers_value[reader],
                "device_id",
            )?)?)
        };
        let alice = account("alice")?;
        let bob = account("bob")?;
        let agent = account("agent")?;
        let agent_method = DidUrl::new(format!("did:web:agent.example#{AGENT_METHOD_FRAGMENT}"))
            .map_err(|error| anyhow!("{error}"))?;
        let mut readers = BTreeMap::new();
        readers.insert(
            "alice_device".to_owned(),
            Reader::Device {
                actor: ActorId::account(alice.clone()),
                device_id: device("alice_device")?,
            },
        );
        readers.insert(
            "bob_device".to_owned(),
            Reader::Device {
                actor: ActorId::account(bob.clone()),
                device_id: device("bob_device")?,
            },
        );
        readers.insert(
            "bob_other_device".to_owned(),
            Reader::Device {
                actor: ActorId::account(bob.clone()),
                device_id: device("bob_other_device")?,
            },
        );
        for (name, authorization, seed) in [
            ("agent_current", "current", AGENT_AUTHORIZE),
            ("agent_replaced", "replacement", AGENT_REPLACED_AUTHORIZE),
        ] {
            ensure!(
                readers_value[name]["authorization"] == authorization,
                "{name} no longer reads under the {authorization} authorization"
            );
            readers.insert(
                name.to_owned(),
                Reader::Agent {
                    agent_id: agent.principal_id.clone(),
                    verification_method: agent_method.clone(),
                    authorize_event_id: event_id(seed),
                },
            );
        }
        let claims = required_field(world, "claims")?;
        let mut claim_ids = BTreeMap::new();
        for name in ["bob_claim", "agent_claim", "unknown_claim"] {
            claim_ids.insert(
                name.to_owned(),
                required_str(&claims[name], "claim_id")?.to_owned(),
            );
        }
        let clocks = required_field(world, "clocks")?
            .as_object()
            .context("clocks")?
            .iter()
            .map(|(name, at)| Ok((name.clone(), timestamp(at)?)))
            .collect::<Result<BTreeMap<_, _>>>()?;
        Ok(Self {
            scope: ScopeRef::Realm {
                realm_id: realm_id.clone(),
            },
            station_id,
            station_method,
            realm_id,
            alice_device: device("alice_device")?,
            bob_device: device("bob_device")?,
            alice,
            bob,
            agent,
            agent_method,
            readers,
            claim_ids,
            claimed_at: timestamp(&world["claimed_at"])?,
            claim_expires_at: timestamp(&world["claim_expires_at"])?,
            retention_ends_at: timestamp(&world["query_retention_ends_at"])?,
            clocks,
        })
    }

    fn clock(&self, variant: &Value) -> Result<DateTime<Utc>> {
        let name = variant["clock"].as_str().unwrap_or("inside_retention");
        self.clocks
            .get(name)
            .copied()
            .with_context(|| format!("unknown clock {name}"))
    }

    fn bob_identity(&self) -> Result<ArkretMlsIdentity> {
        Ok(ArkretMlsIdentity::new_human_device(
            ActorId::account(self.bob.clone()),
            self.bob_device.clone(),
            ArkretMlsSigner::from_ed25519_signing_key(SigningKey::from_bytes(&BOB_SEED)),
        )?)
    }

    fn mls_group_id(&self) -> Result<arkret_wire::MlsGroupId> {
        Ok(self.scope.canonical_mls_group_id()?)
    }

    /// The claim record the Station allocates for one claimed KeyPackage.
    fn claim_record(
        &self,
        claim_id: &str,
        keypackage: &MlsKeyPackageRecord,
        endpoint: ClaimedEndpoint,
    ) -> Result<KeyPackageClaimRecord> {
        let bytes = arkret_canonical::base64url_decode(&keypackage.keypackage)?;
        let (principal, device, agent) = match endpoint {
            ClaimedEndpoint::BobDevice => (
                self.bob.principal_id.clone(),
                Some(self.bob_device.clone()),
                None,
            ),
            ClaimedEndpoint::Agent => (
                self.agent.principal_id.clone(),
                None,
                Some(self.agent.principal_id.clone()),
            ),
        };
        Ok(KeyPackageClaimRecord {
            claim_id: claim_id.to_owned(),
            keypackage_ref: arkret_canonical::sha256_digest(&bytes),
            actor_id: keypackage.actor_id.clone(),
            principal_id: principal,
            device_id: device.clone(),
            agent_id: agent.clone(),
            agent_verification_method: agent.as_ref().map(|_| self.agent_method.clone()),
            pairwise_verification_method: None,
            keypackage: keypackage.keypackage.clone(),
            capabilities: keypackage.capabilities.clone(),
            device_authorize_event_id: device.map(|_| event_id(BOB_AUTHORIZE)),
            agent_key_authorize_event_id: agent.map(|_| event_id(AGENT_AUTHORIZE)),
            expires_at: self.claim_expires_at,
            revocation_status: None,
            last_resort: None,
        })
    }

    /// The first serialized outcome of alice's claim request for `record`,
    /// its receipt signed by the Station's service key.
    fn outcome(
        &self,
        request_seed: u8,
        record: KeyPackageClaimRecord,
        endpoint: ClaimedEndpoint,
    ) -> Result<KeyPackagesClaimOutcome> {
        let claim_request_id =
            Base64UrlString::new(arkret_canonical::base64url_encode([request_seed; 24]))
                .map_err(anyhow::Error::msg)?;
        let required = record
            .capabilities
            .iter()
            .take(1)
            .map(|capability| NonEmptyString::new(capability.clone()).map_err(anyhow::Error::msg))
            .collect::<Result<Vec<_>>>()?;
        let (target_account_id, target_device_ids, agent) = match endpoint {
            ClaimedEndpoint::BobDevice => {
                (Some(self.bob.clone()), vec![self.bob_device.clone()], None)
            }
            ClaimedEndpoint::Agent => (None, Vec::new(), Some(())),
        };
        let request = PeerKeyPackagesClaimUnsignedRequest {
            claim_request_id: claim_request_id.clone(),
            target_account_id,
            requester_account_id: Some(self.alice.clone()),
            intended_realm_id: self.realm_id.clone(),
            mls_group_id: self.mls_group_id()?,
            claim_purpose: PeerKeyPackageClaimPurpose::RealmMembership,
            required_capabilities: required,
            expires_at: self.claim_expires_at,
            target_device_ids,
            target_keypackage_ref: None,
            target_agent_id: agent.map(|()| self.agent.principal_id.clone()),
            target_agent_verification_method: agent.map(|()| self.agent_method.clone()),
            target_agent_key_authorize_event_id: agent.map(|()| event_id(AGENT_AUTHORIZE)),
            target_pairwise_verification_method: None,
            timeout_ms: None,
            strand_id: None,
            pair_key: None,
            last_resort_allowed: None,
        };
        let claims = vec![record];
        let mut receipt = PeerKeyPackageClaimReceipt {
            claim_request_id: claim_request_id.clone(),
            request_digest: Hash::new(arkret_canonical::canonical_sha256(&request)?)?,
            claims_digest: Hash::new(arkret_canonical::canonical_sha256(&claims)?)?,
            source_id: self.station_id.clone(),
            destination_id: self.station_id.clone(),
            request,
            claimed_at: self.claimed_at,
            expires_at: self.claim_expires_at,
            signature: KeyOperationSignature {
                kid: NonEmptyString::new(self.station_method.to_string())
                    .map_err(anyhow::Error::msg)?,
                signature_algorithm: Some(
                    NonEmptyString::new("Ed25519").map_err(anyhow::Error::msg)?,
                ),
                sig: Base64UrlString::new("AA").map_err(anyhow::Error::msg)?,
            },
        };
        sign_receipt(&mut receipt, &SigningKey::from_bytes(&STATION_SEED))?;
        let outcome = KeyPackagesClaimOutcome {
            claim_request_id,
            claim_receipt: receipt,
            claims,
        };
        outcome
            .validate_shape()
            .map_err(|error| anyhow!("fixture claim outcome: {error:?}"))?;
        Ok(outcome)
    }
}

#[derive(Clone, Copy)]
enum ClaimedEndpoint {
    BobDevice,
    Agent,
}

fn sign_receipt(receipt: &mut PeerKeyPackageClaimReceipt, key: &SigningKey) -> Result<()> {
    let bytes = peer_keypackage_claim_receipt_signing_bytes(receipt)?;
    receipt.signature.sig = Base64UrlString::new(arkret_canonical::base64url_encode(
        key.sign(&bytes).to_bytes(),
    ))
    .map_err(anyhow::Error::msg)?;
    Ok(())
}

// ---------------------------------------------------------------------------
// The claim destination
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, PartialEq, Eq)]
struct LedgerRow {
    /// The exact bytes first serialized for the claim request.
    outcome: Vec<u8>,
    claim_state: &'static str,
    keypackage_state: &'static str,
}

struct Station {
    ledger: BTreeMap<String, LedgerRow>,
    retention_ends_at: DateTime<Utc>,
    station_id: DidCoreId,
    /// bob's MLS identity; `bob_private_state` snapshots it with the
    /// claimed KeyPackage's private material, which only a verified Welcome
    /// may consume.
    bob_identity: ArkretMlsIdentity,
    bob_private_state: Vec<u8>,
    bob_keypackage: MlsKeyPackageRecord,
}

impl Station {
    fn new(world: &World) -> Result<Self> {
        let bob_identity = world.bob_identity()?;
        let bob_keypackage = bob_identity.key_package_record()?;
        let agent_identity = ArkretMlsIdentity::new_agent(
            ActorId::account(world.agent.clone()),
            world.agent_method.clone(),
            event_id(AGENT_AUTHORIZE),
            ArkretMlsSigner::from_ed25519_signing_key(SigningKey::from_bytes(&AGENT_SEED)),
        )?;
        let agent_keypackage = agent_identity.key_package_record()?;
        let mut ledger = BTreeMap::new();
        for (name, keypackage, endpoint, seed) in [
            (
                "bob_claim",
                &bob_keypackage,
                ClaimedEndpoint::BobDevice,
                0x41,
            ),
            (
                "agent_claim",
                &agent_keypackage,
                ClaimedEndpoint::Agent,
                0x42,
            ),
        ] {
            let claim_id = &world.claim_ids[name];
            let record = world.claim_record(claim_id, keypackage, endpoint)?;
            let outcome = world.outcome(seed, record, endpoint)?;
            ledger.insert(
                claim_id.clone(),
                LedgerRow {
                    outcome: arkret_canonical::canonical_json_bytes(&outcome)?,
                    claim_state: "claimed",
                    keypackage_state: "claimed",
                },
            );
        }
        Ok(Self {
            ledger,
            retention_ends_at: world.retention_ends_at,
            station_id: world.station_id.clone(),
            bob_private_state: bob_identity.export_private_state()?,
            bob_identity,
            bob_keypackage,
        })
    }

    /// `ak.self.keys.keypackages.read.claim.v1`: the stored bytes for the
    /// claim record's exact endpoint, `keypackage_unknown` for everything
    /// else. Nothing is written.
    fn read(
        &self,
        reader: &Reader,
        claim_id: &str,
        at: DateTime<Utc>,
    ) -> std::result::Result<Vec<u8>, &'static str> {
        const UNKNOWN: &str = "keypackage_unknown";
        let row = self
            .ledger
            .get(claim_id)
            .filter(|_| at < self.retention_ends_at)
            .ok_or(UNKNOWN)?;
        let outcome: KeyPackagesClaimOutcome =
            serde_json::from_slice(&row.outcome).map_err(|_| UNKNOWN)?;
        let owned = outcome.claim_receipt.destination_id == self.station_id
            && outcome
                .claims
                .iter()
                .find(|record| record.claim_id == claim_id)
                .is_some_and(|record| names_reader(record, reader));
        if owned {
            Ok(row.outcome.clone())
        } else {
            Err(UNKNOWN)
        }
    }

    fn states(&self) -> (&'static str, &'static str) {
        let common = |state: fn(&LedgerRow) -> &'static str| {
            let mut states = self.ledger.values().map(state);
            let first = states.next().unwrap_or("absent");
            if states.all(|next| next == first) {
                first
            } else {
                "mixed"
            }
        };
        (
            common(|row| row.claim_state),
            common(|row| row.keypackage_state),
        )
    }

    fn read_variant(&mut self, world: &World, variant: &Value) -> Result<Value> {
        ensure!(variant["operation_id"] == "ak.self.keys.keypackages.read.claim.v1");
        let reader = world
            .readers
            .get(required_str(variant, "reader")?)
            .context("unknown reader")?;
        let claim_id = world
            .claim_ids
            .get(required_str(variant, "claim")?)
            .context("unknown claim")?;
        let before = self.ledger.clone();
        let answer = self.read(reader, claim_id, world.clock(variant)?);
        let state_writes = self
            .ledger
            .iter()
            .filter(|(id, row)| before.get(*id) != Some(row))
            .count()
            + before.len().abs_diff(self.ledger.len());
        let (claim_state, keypackage_state) = self.states();
        Ok(match answer {
            Ok(bytes) => {
                let stored = &self.ledger[claim_id].outcome;
                let parsed: KeyPackagesClaimOutcome = serde_json::from_slice(&bytes)?;
                parsed
                    .validate_shape()
                    .map_err(|error| anyhow!("served outcome: {error:?}"))?;
                json!({
                    "decision": "accept",
                    "outcome": if &bytes == stored { "original_bytes" } else { "other_bytes" },
                    "state_writes": state_writes,
                    "claim_state": claim_state,
                    "keypackage_state": keypackage_state,
                })
            }
            Err(code) => json!({
                "decision": "reject",
                "error_code": code,
                "state_writes": state_writes,
                "claim_state": claim_state,
                "keypackage_state": keypackage_state,
            }),
        })
    }
}

/// Whether `record` is the claim of exactly `reader`'s endpoint: a human
/// device by its complete AccountId and device, an Agent by its id, method
/// and current authorization.
fn names_reader(record: &KeyPackageClaimRecord, reader: &Reader) -> bool {
    match reader {
        Reader::Device { actor, device_id } => {
            &record.actor_id == actor
                && record.device_id.as_ref() == Some(device_id)
                && record.agent_id.is_none()
                && record.agent_verification_method.is_none()
        }
        Reader::Agent {
            agent_id,
            verification_method,
            authorize_event_id,
        } => {
            record.agent_id.as_ref() == Some(agent_id)
                && record.agent_verification_method.as_ref() == Some(verification_method)
                && record.agent_key_authorize_event_id.as_ref() == Some(authorize_event_id)
                && record.device_id.is_none()
        }
    }
}

// ---------------------------------------------------------------------------
// The recipient
// ---------------------------------------------------------------------------

/// alice's accepted Add Commit of one of bob's KeyPackages, with bob's
/// Welcome naming `bob_claim`.
struct AddCommit {
    accepted: CommittedEventFullView,
    welcome: MlsWelcomeDelivery,
}

struct Recipient {
    /// The Add of exactly the claimed KeyPackage.
    claimed: AddCommit,
    /// The Add of another of bob's KeyPackages, its Welcome still naming
    /// `bob_claim`.
    other: AddCommit,
}

impl Recipient {
    fn new(world: &World, station: &Station) -> Result<Self> {
        let other_keypackage = station.bob_identity.key_package_record()?;
        let claimed = |record: &MlsKeyPackageRecord, claim_id: &str| MlsKeyPackageRecord {
            state: arkret_models_crypto::MlsKeyPackageState::Claimed,
            claim_id: Some(claim_id.to_owned()),
            ..record.clone()
        };
        Ok(Self {
            claimed: add_commit(
                world,
                &claimed(&station.bob_keypackage, &world.claim_ids["bob_claim"]),
                0x81,
            )?,
            // The Commit adds bob's other KeyPackage under a claim of its own.
            other: add_commit(
                world,
                &claimed(
                    &other_keypackage,
                    "ak:keypackage_claim:0199d100-0000-7000-8000-000000000103",
                ),
                0x82,
            )?,
        })
    }

    fn receive(&mut self, world: &World, station: &Station, variant: &Value) -> Result<Value> {
        let refused = |by: &str| {
            json!({
                "decision": "reject",
                "decrypted": false,
                "refused_by": by,
            })
        };
        let reader = &world.readers["bob_device"];
        let claim_id = &world.claim_ids[required_str(variant, "claim")?];
        let Ok(bytes) = station.read(reader, claim_id, world.clock(variant)?) else {
            return Ok(refused("claim_read"));
        };
        let mut outcome: KeyPackagesClaimOutcome = serde_json::from_slice(&bytes)?;
        match variant["tamper"].as_str() {
            None => {}
            Some("claim_capabilities") => outcome.claims[0]
                .capabilities
                .push("ak.content.extra.v1".to_owned()),
            Some("receipt_signature") => sign_receipt(
                &mut outcome.claim_receipt,
                &SigningKey::from_bytes(&FOREIGN_SEED),
            )?,
            Some(other) => bail!("unknown tamper {other}"),
        }
        if outcome.validate_shape().is_err() {
            return Ok(refused("claims_digest"));
        }
        if !receipt_verifies(&outcome.claim_receipt)? {
            return Ok(refused("claim_receipt_signature"));
        }
        let add = match variant["commit_adds"].as_str() {
            None => &self.claimed,
            Some("bob_other_keypackage") => &self.other,
            Some(other) => bail!("unknown commit_adds {other}"),
        };
        let authorization = match variant["endpoint_authorization"].as_str() {
            None => event_id(BOB_AUTHORIZE),
            Some("replaced") => event_id(BOB_REPLACED_AUTHORIZE),
            Some(other) => bail!("unknown endpoint_authorization {other}"),
        };
        let endpoint = LocalMlsEndpoint::device(
            world.realm_id.clone(),
            ActorId::account(world.bob.clone()),
            world.bob_device.clone(),
        );
        if verify_welcome_claim(
            &add.welcome,
            &endpoint,
            &add.accepted.event,
            &outcome,
            &world.station_id,
            &authorization,
        )
        .is_err()
        {
            return Ok(refused("welcome_claim_binding"));
        }
        let identity = ArkretMlsIdentity::restore_from_private_state(
            ActorId::account(world.bob.clone()),
            station.bob_identity.endpoint_identity(),
            &station.bob_private_state,
        )?;
        let group = ArkretMlsGroup::join_from_verified_welcome_delivery(
            identity,
            &add.welcome,
            &add.accepted,
        )?;
        Ok(json!({
            "decision": "accept",
            "decrypted": true,
            "joined_epoch": group.epoch(),
        }))
    }
}

fn receipt_verifies(receipt: &PeerKeyPackageClaimReceipt) -> Result<bool> {
    let bytes = peer_keypackage_claim_receipt_signing_bytes(receipt)?;
    let Ok(sig) = arkret_canonical::base64url_decode(receipt.signature.sig.as_str()) else {
        return Ok(false);
    };
    let Ok(signature) = ed25519_dalek::Signature::from_slice(&sig) else {
        return Ok(false);
    };
    Ok(SigningKey::from_bytes(&STATION_SEED)
        .verifying_key()
        .verify(&bytes, &signature)
        .is_ok())
}

/// alice's epoch-0 group, the accepted inline Add of `keypackage` at epoch 1
/// and bob's producer-signed Welcome naming `bob_claim`.
fn add_commit(world: &World, keypackage: &MlsKeyPackageRecord, seed: u8) -> Result<AddCommit> {
    let alice_key = SigningKey::from_bytes(&ALICE_SEED);
    let alice = ArkretMlsIdentity::new_human_device(
        ActorId::account(world.alice.clone()),
        world.alice_device.clone(),
        ArkretMlsSigner::from_ed25519_signing_key(alice_key.clone()),
    )?;
    let genesis = MlsGovernanceBindingPayload::new(world.scope.clone(), None, 0, 0, 0)?;
    let mut group = alice.create_group_with_governance_binding(&world.scope, &genesis)?;
    let binding =
        MlsGovernanceBindingPayload::new(world.scope.clone(), Some(event_id(GENESIS)), 0, 1, 0)?;
    let add = group.add_member_with_governance_binding(keypackage, &binding)?;
    let payload = MlsCommitPayload::new(event_id(GENESIS), 0, &add.commit, binding)?;
    let method = format!(
        "did:web:alice.example#{}",
        world
            .alice_device
            .as_str()
            .rsplit(':')
            .next()
            .unwrap_or("device")
    );
    let created_at = world.claimed_at;
    let event = sign(
        arkret_wire::test_support::raw_event_for_actor_at(
            EventKind::MlsCommit.as_str(),
            world.scope.clone(),
            ActorId::account(world.alice.clone()),
            serde_json::to_value(&payload)?,
            created_at,
        )?,
        &method,
        ALICE_SEED,
        created_at,
    )?;
    let accepted = CommittedEventFullView {
        commit: accepted_commit(&event, seed)?,
        event: event.clone(),
    };
    accepted.validate_shape()?;
    let welcome = signed_welcome(world, &event, &method, &alice_key, &add.welcome, seed)?;
    Ok(AddCommit { accepted, welcome })
}

fn accepted_commit(event: &Event, seed: u8) -> Result<RealmCommit> {
    let commit_id = |fill: u8| {
        format!(
            "ak:realm_commit:{}",
            arkret_wire::EventId::from_digest(DigestSuite::Sha256, [fill; 32])
                .as_str()
                .trim_start_matches("ak:event:")
        )
    };
    Ok(serde_json::from_value(json!({
        "commit_id": commit_id(seed),
        "realm_id": event.realm_id,
        "stream_ref": event.scope_ref,
        "stream_position": 1,
        "previous_commit_ref": commit_id(seed.wrapping_add(1)),
        "event_ref": event.event_id,
        "governance_generation": 0,
        "authority_ref": event.event_id,
        "committed_at": "2026-09-26T01:01:00.000Z",
        "signature": {
            "context": "ak.realm_commit_signature.v1",
            "signature_algorithm": "Ed25519",
            "verification_method": "did:web:governance.example#authority",
            "signed_digest": format!("sha256:{}", "4".repeat(64)),
            "created_at": "2026-09-26T01:01:00.000Z",
            "sig": "A".repeat(86),
        },
    }))?)
}

fn signed_welcome(
    world: &World,
    commit: &Event,
    method: &str,
    key: &SigningKey,
    draft: &arkret::MlsWelcomeDraft,
    seed: u8,
) -> Result<MlsWelcomeDelivery> {
    let method = DidUrl::new(method.to_owned()).map_err(|error| anyhow!("{error}"))?;
    let mut delivery = MlsWelcomeDelivery {
        welcome_id: MlsWelcomeDeliveryId::new(format!(
            "ak:mls_welcome_delivery:0199d100-0000-7000-8000-0000000003{seed:02x}"
        ))?,
        realm_id: commit.realm_id.clone(),
        effective_scope: commit.scope_ref.clone(),
        commit_event_ref: commit.event_id.clone(),
        recipient_actor_id: ActorId::account(world.bob.clone()),
        recipient_endpoint: MlsWelcomeRecipientEndpoint::Device {
            device_id: world.bob_device.clone(),
        },
        keypackage_claim_ref: KeypackageClaimId::new(world.claim_ids["bob_claim"].clone())?,
        ciphertext_b64: draft.ciphertext_b64.clone(),
        producer_proof: arkret_wire::DetachedObjectSignature {
            context: DetachedSignatureContext::MlsWelcomeDelivery,
            signature_algorithm: DetachedSignatureAlgorithm::Ed25519,
            verification_method: method.clone(),
            signed_digest: Hash::new(format!("sha256:{}", "0".repeat(64)))?,
            created_at: world.claimed_at,
            sig: Base64UrlString::new("AA").map_err(anyhow::Error::msg)?,
        },
    };
    let mut unsigned = serde_json::to_value(&delivery)?;
    unsigned
        .as_object_mut()
        .context("a Welcome delivery is an object")?
        .remove("producer_proof");
    delivery.producer_proof = arkret_signatures::detached_object::sign_detached_object(
        &unsigned,
        DetachedSignatureContext::MlsWelcomeDelivery,
        method,
        world.claimed_at,
        key,
    )?;
    delivery.validate_shape()?;
    Ok(delivery)
}
