//! Cross-process minimal-metadata pairwise KeyPackage coverage.
//!
//! This scenario uses a pre-built Soland process and real RFC 9420
//! KeyPackages generated by `ArkretMlsIdentity`. The authenticated human
//! session is transport authority only: neither pairwise actor has an account,
//! device authorization, or session whose actor equals the pairwise DID.

use std::time::Duration;

use anyhow::{Context as _, Result, bail, ensure};
use arkret::mls::{ArkretMlsGroup, ArkretMlsIdentity, ArkretMlsSigner};
use arkret::{
    Base64UrlString, ContentScheme, DeviceId, Did, DidCoreId, DidUrl, KeyOperationSignature,
    KeyPackagesClaimOutcome, KeyPackagesClaimRequestBody, KeyPackagesClaimServiceBinding,
    KeyPackagesConsumeOutcome, KeyPackagesUploadOutcome, MlsKeyPackageRecord, NonEmptyString,
    PeerKeyPackageClaimPurpose, PeerKeyPackageRequesterAuthorization,
    PeerKeyPackagesClaimUnsignedRequest, RealmId, RecipientMlsDurableReceipt,
    RecipientMlsDurableSigner, keypackage_claim_authorization_signing_bytes,
    keypackages_upload_signing_input, mls_key_package_record_upload_entry,
};
use arkret_models_collaboration::events_payloads::{
    MlsClaimTrustBinding, MlsRequesterTrustBinding, MlsWelcomeCarrier, MlsWelcomeClaimEnvelope,
    MlsWelcomeClaimEnvelopeSigningInput, MlsWelcomePayload, MlsWelcomePayloadClaimRef,
    MlsWelcomeRecipient, UnsignedMlsWelcomeClaimEnvelope,
};
use arkret_models_collaboration::governance::membership_invite::{
    MembershipPayload, MembershipPayloadState,
};
use arkret_models_crypto::{MlsCommitPayload, MlsGovernanceBindingPayload};
use arkret_wire::cbs::{Precondition, Predicate, PredicateOp};
use arkret_wire::{AccountId, ActorId, Event, EventId, EventKind, Hash, ScopeRef};
use base64::Engine as _;
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use chrono::Utc;
use ed25519_dalek::{Signer as _, SigningKey};
use reqwest::{Response, StatusCode};
use serde_json::{Value, json};

use crate::harness::{ArkretServer, ProvisionedTestPrincipal, TestActorClient, expect_json};
use crate::scenarios::_helpers::external_binary::{SOLAND_SPEC, locate_external_binary};
use crate::scenarios::identity_test_support::actor_did_for_service_did;

const UPLOAD_PATH: &str = "/_arkret/self/keys/keypackages/upload";
const CLAIM_PATH: &str = "/_arkret/self/keys/keypackages/claim";
const CONSUME_PATH: &str = "/_arkret/self/keys/keypackages/consume";
const TRANSPORT_DEVICE: &str = "ak:device:01904100-0000-7000-8000-000000001423";
const OTHER_ORDINARY_DEVICE: &str = "ak:device:01904100-0000-7000-8000-000000001427";
const TARGET_SEED: [u8; 32] = [0x42; 32];
const REQUESTER_SEED: [u8; 32] = [0x24; 32];
const OTHER_SEED: [u8; 32] = [0x66; 32];

fn wire_value<T>(value: std::result::Result<T, &'static str>) -> Result<T> {
    value.map_err(anyhow::Error::msg)
}

#[derive(Clone)]
struct PairwiseKey {
    seed: [u8; 32],
    did: Did,
    actor_id: DidCoreId,
    verification_method: DidUrl,
}

impl PairwiseKey {
    fn from_seed(seed: [u8; 32]) -> Result<Self> {
        let public_key = SigningKey::from_bytes(&seed).verifying_key().to_bytes();
        let multibase = arkret_canonical::ed25519_pubkey_to_did_key_multibase(&public_key);
        Ok(Self {
            seed,
            did: Did::new(format!("did:key:{multibase}"))?,
            actor_id: DidCoreId::new(format!("ak:did_core:key:{multibase}"))?,
            verification_method: wire_value(DidUrl::new(format!(
                "did:key:{multibase}#{multibase}"
            )))?,
        })
    }

    fn identity(&self) -> Result<ArkretMlsIdentity> {
        ArkretMlsIdentity::new_minimal_metadata_pairwise(
            self.actor_id.clone(),
            self.verification_method.clone(),
            ArkretMlsSigner::from_ed25519_signing_key(SigningKey::from_bytes(&self.seed)),
        )
        .map_err(anyhow::Error::from)
    }

    fn signature(&self, bytes: &[u8]) -> Result<KeyOperationSignature> {
        Ok(KeyOperationSignature {
            kid: wire_value(NonEmptyString::new(self.verification_method.to_string()))?,
            signature_algorithm: Some(wire_value(NonEmptyString::new("Ed25519"))?),
            sig: wire_value(Base64UrlString::new(
                URL_SAFE_NO_PAD.encode(SigningKey::from_bytes(&self.seed).sign(bytes).to_bytes()),
            ))?,
        })
    }
}

/// Run the cross-process ordinary-first and reusable-last-resort lifecycle.
/// Both claims are carried through real RFC 9420 Welcome joins, accepted
/// Events, recipient durable receipts, single-source consume, and exact replay.
pub async fn run_minimal_metadata_pairwise_keypackage_live() -> Result<()> {
    if locate_external_binary(&SOLAND_SPEC).is_none() {
        eprintln!(
            "skipping minimal-metadata pairwise KeyPackage live scenario: pre-built Soland is unavailable"
        );
        return Ok(());
    }

    let server = ArkretServer::spawn("pairwise-keypackage-live").await?;
    let transport_did = actor_did_for_service_did(server.service_did(), "pairwise-transport")?;
    let transport = server
        .register_client(&transport_did, "pairwise-transport", TRANSPORT_DEVICE)
        .await?;
    let target = PairwiseKey::from_seed(TARGET_SEED)?;
    let requester = PairwiseKey::from_seed(REQUESTER_SEED)?;
    let other = PairwiseKey::from_seed(OTHER_SEED)?;

    ensure!(
        transport.actor != target.did.as_str() && transport.actor != requester.did.as_str(),
        "pairwise coverage must not authenticate as either pairwise actor"
    );

    let realm_id = create_pairwise_realm(&transport, "Pairwise KeyPackage live", true).await?;
    let wrong_realm_id = create_pairwise_realm(&transport, "Pairwise wrong Realm", true).await?;
    let ordinary_realm_id = create_pairwise_realm(&transport, "Ordinary MLS Realm", false).await?;
    install_pairwise_membership(&transport, &realm_id, &target).await?;
    install_pairwise_membership(&transport, &realm_id, &requester).await?;
    install_pairwise_membership(&transport, &ordinary_realm_id, &target).await?;

    let target_identity = target.identity()?;
    let last_resort_identity = target.identity()?;
    let target_record = target_identity.key_package_record()?;
    let mut last_resort_record = last_resort_identity.key_package_record()?;
    last_resort_record.last_resort = true;
    let upload = target_identity.signed_key_packages_upload_request(
        &[target_record.clone(), last_resort_record.clone()],
        target.verification_method.as_str(),
        Some(RealmId::new(realm_id.clone())?),
    )?;
    let upload_value = serde_json::to_value(&upload)?;
    ensure!(
        upload_value.get("device_id").is_none()
            && upload_value.get("agent_verification_method").is_none()
            && upload_value.get("agent_key_authorize_event_id").is_none(),
        "pairwise upload leaked a device or Agent mixed branch"
    );

    reject_upload_mutation(&transport, &upload, |value| {
        value["device_id"] = json!(TRANSPORT_DEVICE);
    })
    .await
    .context("mixed device/pairwise upload branch")?;
    reject_upload_mutation(&transport, &upload, |value| {
        value["principal_id"] = json!(other.actor_id);
    })
    .await
    .context("upload actor/method mismatch")?;
    reject_upload_mutation(&transport, &upload, |value| {
        value["intended_realm_id"] = json!(wrong_realm_id);
    })
    .await
    .context("upload wrong Realm affinity")?;
    reject_upload_mutation(&transport, &upload, |value| {
        value["intended_realm_id"] = json!(ordinary_realm_id);
    })
    .await
    .context("ordinary MLS Realm accepted the minimal-metadata pairwise branch")?;
    reject_upload_mutation(&transport, &upload, |value| {
        value["keypackages"]
            .as_array_mut()
            .expect("typed batch")
            .reverse();
    })
    .await
    .context("batch entry order tamper")?;
    reject_upload_mutation(&transport, &upload, |value| {
        value["keypackages"]
            .as_array_mut()
            .expect("typed batch")
            .pop();
    })
    .await
    .context("batch entry count tamper")?;

    let other_identity = other.identity()?;
    let other_record = other_identity.key_package_record()?;
    let wrong_credential = signed_pairwise_upload_with_records(
        &target,
        std::slice::from_ref(&other_record),
        &realm_id,
    )?;
    assert_upload_entries_rejected(&transport, &wrong_credential)
        .await
        .context("batch-authorized KeyPackage credential from another actor")?;

    let wrong_key_identity = ArkretMlsIdentity::new_minimal_metadata_pairwise(
        target.actor_id.clone(),
        other.verification_method.clone(),
        ArkretMlsSigner::from_ed25519_signing_key(SigningKey::from_bytes(&OTHER_SEED)),
    )?;
    let wrong_key_record = wrong_key_identity.key_package_record()?;
    let wrong_key = signed_pairwise_upload_with_records(
        &target,
        std::slice::from_ref(&wrong_key_record),
        &realm_id,
    )?;
    assert_upload_entries_rejected(&transport, &wrong_key)
        .await
        .context("batch-authorized KeyPackage with a different Leaf signature key")?;

    let mut invalid_self_signature_record = target.identity()?.key_package_record()?;
    let mut invalid_bytes = URL_SAFE_NO_PAD.decode(&invalid_self_signature_record.keypackage)?;
    let last = invalid_bytes
        .last_mut()
        .context("real KeyPackage bytes are empty")?;
    *last ^= 0x01;
    invalid_self_signature_record.keypackage = URL_SAFE_NO_PAD.encode(&invalid_bytes);
    invalid_self_signature_record.keypackage_ref =
        Hash::new(arkret_canonical::sha256_digest(&invalid_bytes))?;
    let invalid_self_signature = signed_pairwise_upload_with_records(
        &target,
        std::slice::from_ref(&invalid_self_signature_record),
        &realm_id,
    )?;
    assert_upload_entries_rejected(&transport, &invalid_self_signature)
        .await
        .context("batch-authorized KeyPackage with an invalid RFC 9420 self-signature")?;

    let upload_outcome: KeyPackagesUploadOutcome = serde_json::from_value(
        expect_json(transport.post(UPLOAD_PATH).json(&upload), StatusCode::OK).await?,
    )?;
    ensure!(
        upload_outcome.accepted == 2
            && upload_outcome.rejections.is_empty()
            && upload_outcome
                .key_package_refs
                .iter()
                .any(|reference| reference == target_record.keypackage_ref.as_str())
            && upload_outcome
                .key_package_refs
                .iter()
                .any(|reference| reference == last_resort_record.keypackage_ref.as_str()),
        "pairwise upload did not accept both ordinary and last-resort RFC 9420 KeyPackages: {upload_outcome:?}"
    );

    let principal = transport
        .principal
        .as_ref()
        .context("pairwise transport omitted its provisioned principal")?
        .clone();
    verify_ordinary_keypackage_binding_matrix(&transport, &principal, &ordinary_realm_id).await?;
    let requester_identity = ArkretMlsIdentity::new_human_device(
        principal.core_id.clone(),
        principal.device_id.clone(),
        ArkretMlsSigner::from_ed25519_signing_key(principal.device_signing_key.clone()),
    )?;
    let canonical_group_id = ScopeRef::Realm {
        realm_id: RealmId::new(realm_id.clone())?,
    }
    .canonical_mls_group_id()?;
    let group_id_seed = arkret_canonical::base64url_decode(canonical_group_id.as_bytes())?;
    let genesis_binding = governance_binding(&realm_id, &canonical_group_id, 0, 0)?;
    let mut requester_group = requester_identity
        .create_group_with_governance_binding(&group_id_seed, &genesis_binding)?;
    ensure!(
        requester_group.group_id() == canonical_group_id,
        "OpenMLS group id did not retain the canonical Realm scope binding"
    );
    let negative_claim = signed_pairwise_claim(
        &requester,
        &target,
        &realm_id,
        requester_group.group_id(),
        server.service_id().clone(),
        server.service_id().clone(),
    )?;
    let claim_value = serde_json::to_value(&negative_claim)?;
    ensure!(
        claim_value.get("target_device_ids").is_none()
            && claim_value.get("target_agent_id").is_none()
            && claim_value["requester_authorization"]
                .get("requester_device_id")
                .is_none()
            && claim_value["requester_authorization"]
                .get("requester_agent_id")
                .is_none(),
        "pairwise claim leaked a device or Agent mixed branch"
    );

    let mut wrong_method = serde_json::to_value(&negative_claim)?;
    wrong_method["requester_authorization"]["verification_method"] =
        json!(other.verification_method);
    assert_rejected(
        transport
            .post(CLAIM_PATH)
            .json(&wrong_method)
            .send()
            .await?,
    )
    .await?;

    let wrong_realm_claim = signed_pairwise_claim(
        &requester,
        &target,
        &wrong_realm_id,
        requester_group.group_id(),
        server.service_id().clone(),
        server.service_id().clone(),
    )?;
    assert_rejected(
        transport
            .post(CLAIM_PATH)
            .json(&wrong_realm_claim)
            .send()
            .await?,
    )
    .await?;

    let wrong_delivery = DidCoreId::new("ak:did_core:web:wrong-delivery.example".to_owned())?;
    let wrong_delivery_claim = signed_pairwise_claim(
        &requester,
        &target,
        &realm_id,
        requester_group.group_id(),
        server.service_id().clone(),
        wrong_delivery,
    )?;
    assert_rejected(
        transport
            .post(CLAIM_PATH)
            .json(&wrong_delivery_claim)
            .send()
            .await?,
    )
    .await?;

    let genesis_event = submit_and_settle_control_event(
        &transport,
        &realm_id,
        EventKind::MlsGenesis.as_str(),
        json!({
            "mls_group_id": canonical_group_id,
            "effective_scope": {"kind": "realm", "realm_id": realm_id},
            "epoch": 0,
            "cipher_suite": "MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519",
            "group_info_ref": format!("ak:blob:sha256:{}", "3".repeat(64)),
            "ratchet_tree_ref": format!("ak:blob:sha256:{}", "4".repeat(64)),
            "governance_binding": genesis_binding,
            "created_at": Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Millis, true)
        }),
    )
    .await?;

    let ordinary_claim = signed_device_claim(
        &principal,
        &target,
        &realm_id,
        requester_group.group_id(),
        server.service_id(),
        "ordinary",
        true,
    )?;
    let ordinary_outcome = claim_keypackage(&transport, &ordinary_claim).await?;
    assert_claimed_pairwise_record(&ordinary_outcome, &target, &target_record, false)?;
    let first_commit = accept_welcome_and_consume(
        &transport,
        &realm_id,
        &principal,
        &target,
        target_identity,
        &mut requester_group,
        &target_record,
        &ordinary_outcome,
        0,
        &genesis_event,
    )
    .await?;
    // Rotate the first pairwise leaf out before exercising the reusable
    // KeyPackage. MLS forbids duplicate leaf signature keys; the Realm
    // membership and pairwise endpoint authority remain current throughout.
    let removal_commit = remove_pairwise_leaf(
        &transport,
        &realm_id,
        &target,
        &mut requester_group,
        1,
        &first_commit,
    )
    .await?;

    let last_resort_claim = signed_device_claim(
        &principal,
        &target,
        &realm_id,
        requester_group.group_id(),
        server.service_id(),
        "last-resort-first",
        true,
    )?;
    let last_resort_outcome = claim_keypackage(&transport, &last_resort_claim).await?;
    assert_claimed_pairwise_record(&last_resort_outcome, &target, &last_resort_record, true)?;
    accept_welcome_and_consume(
        &transport,
        &realm_id,
        &principal,
        &target,
        last_resort_identity,
        &mut requester_group,
        &last_resort_record,
        &last_resort_outcome,
        2,
        &removal_commit,
    )
    .await?;

    let reusable_claim = signed_device_claim(
        &principal,
        &target,
        &realm_id,
        requester_group.group_id(),
        server.service_id(),
        "last-resort-reuse",
        true,
    )?;
    let reusable_outcome = claim_keypackage(&transport, &reusable_claim).await?;
    assert_claimed_pairwise_record(&reusable_outcome, &target, &last_resort_record, true)?;
    ensure!(
        reusable_outcome.claims[0].claim_id != last_resort_outcome.claims[0].claim_id
            && reusable_outcome.claims[0].keypackage_ref
                == last_resort_outcome.claims[0].keypackage_ref
            && reusable_outcome.claims[0].keypackage_ref != target_record.keypackage_ref.as_str(),
        "post-consume claim did not create an independent audit for the still-published last-resort KeyPackage"
    );

    leave_pairwise_member(&transport, &realm_id, &target).await?;
    let replacement_identity = target.identity()?;
    let replacement = replacement_identity.key_package_record()?;
    let replacement_upload = replacement_identity.signed_key_packages_upload_request(
        &[replacement],
        target.verification_method.as_str(),
        Some(RealmId::new(realm_id)?),
    )?;
    assert_rejected(
        transport
            .post(UPLOAD_PATH)
            .json(&replacement_upload)
            .send()
            .await?,
    )
    .await
    .context("revoked current pairwise membership still authorized upload")?;

    Ok(())
}

async fn verify_ordinary_keypackage_binding_matrix(
    client: &TestActorClient,
    principal: &ProvisionedTestPrincipal,
    realm_id: &str,
) -> Result<()> {
    let valid_identity = ArkretMlsIdentity::new_human_device(
        principal.core_id.clone(),
        principal.device_id.clone(),
        ArkretMlsSigner::from_ed25519_signing_key(principal.device_signing_key.clone()),
    )?;
    let valid_record = valid_identity.key_package_record()?;
    let valid = signed_ordinary_upload_with_records(
        principal,
        std::slice::from_ref(&valid_record),
        realm_id,
    )?;

    let wrong_device_identity = ArkretMlsIdentity::new_human_device(
        principal.core_id.clone(),
        DeviceId::new(OTHER_ORDINARY_DEVICE.to_owned())?,
        ArkretMlsSigner::from_ed25519_signing_key(principal.device_signing_key.clone()),
    )?;
    let wrong_device = signed_ordinary_upload_with_records(
        principal,
        &[wrong_device_identity.key_package_record()?],
        realm_id,
    )?;
    assert_upload_entries_rejected(client, &wrong_device)
        .await
        .context("batch-authorized ordinary KeyPackage credential from another DeviceId")?;

    let wrong_key_signer = SigningKey::from_bytes(&OTHER_SEED);
    let wrong_key_identity = ArkretMlsIdentity::new_human_device(
        principal.core_id.clone(),
        principal.device_id.clone(),
        ArkretMlsSigner::from_ed25519_signing_key(wrong_key_signer),
    )?;
    let wrong_key = signed_ordinary_upload_with_records(
        principal,
        &[wrong_key_identity.key_package_record()?],
        realm_id,
    )?;
    assert_upload_entries_rejected(client, &wrong_key)
        .await
        .context("batch-authorized ordinary KeyPackage with the wrong Leaf signature key")?;

    let mut invalid_self_signature_record = valid_identity.key_package_record()?;
    let mut invalid_bytes = URL_SAFE_NO_PAD.decode(&invalid_self_signature_record.keypackage)?;
    *invalid_bytes
        .last_mut()
        .context("real ordinary KeyPackage bytes are empty")? ^= 0x01;
    invalid_self_signature_record.keypackage = URL_SAFE_NO_PAD.encode(&invalid_bytes);
    invalid_self_signature_record.keypackage_ref =
        Hash::new(arkret_canonical::sha256_digest(&invalid_bytes))?;
    let invalid_self_signature =
        signed_ordinary_upload_with_records(principal, &[invalid_self_signature_record], realm_id)?;
    assert_upload_entries_rejected(client, &invalid_self_signature)
        .await
        .context("batch-authorized ordinary KeyPackage with invalid RFC 9420 self-signature")?;

    let outcome_value = expect_json(client.post(UPLOAD_PATH).json(&valid), StatusCode::OK).await?;
    let outcome: KeyPackagesUploadOutcome = serde_json::from_value(outcome_value)?;
    ensure!(
        outcome.accepted == 1
            && outcome.rejections.is_empty()
            && outcome.key_package_refs == [valid_record.keypackage_ref.to_string()],
        "ordinary RFC 9420 KeyPackage was not accepted: {outcome:?}"
    );
    Ok(())
}

async fn create_pairwise_realm(
    client: &TestActorClient,
    title: &str,
    minimal_metadata: bool,
) -> Result<String> {
    let mut schema_refs = vec![arkret_wire::SchemaId::REALM_V1.to_owned()];
    if minimal_metadata {
        schema_refs.push(arkret_wire::ProfileId::MLS_MINIMAL_METADATA_REALM_V1.to_owned());
    }
    let bootstrap = client
        .create_realm_bootstrap_with(json!({
            "title": title,
            "summary": title,
            "public": false,
            "schema_refs": schema_refs,
            "encryption_profile": "mls_rfc9420",
            "plaintext_visible_services": [client.service_id()]
        }))
        .await?;
    let realm_id = bootstrap["realm_id"]
        .as_str()
        .context("pairwise Realm bootstrap omitted realm_id")?
        .to_owned();
    wait_for_bootstrap_seal(client, &realm_id).await?;
    Ok(realm_id)
}

async fn install_pairwise_membership(
    client: &TestActorClient,
    realm_id: &str,
    pairwise: &PairwiseKey,
) -> Result<()> {
    let payload = MembershipPayload::join(
        RealmId::new(realm_id.to_owned())?,
        ActorId::account(arkret_wire::AccountId::new(
            pairwise.actor_id.clone(),
            DidCoreId::new(client.service_id().to_owned())?,
        )),
        "minimal-metadata pairwise KeyPackage live fixture",
    )
    .to_value()?;
    submit_and_settle_member_transition(client, realm_id, payload).await?;
    Ok(())
}

async fn leave_pairwise_member(
    client: &TestActorClient,
    realm_id: &str,
    pairwise: &PairwiseKey,
) -> Result<()> {
    let payload = MembershipPayload::transition(
        MembershipPayloadState::Leave,
        ActorId::account(arkret_wire::AccountId::new(
            pairwise.actor_id.clone(),
            DidCoreId::new(client.service_id().to_owned())?,
        )),
        "pairwise authority revoked",
    )
    .with_realm_id(RealmId::new(realm_id.to_owned())?)
    .to_value()?;
    submit_and_settle_member_transition(client, realm_id, payload).await?;
    Ok(())
}

async fn submit_and_settle_member_transition(
    client: &TestActorClient,
    realm_id: &str,
    payload: Value,
) -> Result<EventId> {
    Ok(
        submit_and_settle_control_event(client, realm_id, EventKind::MemberState.as_str(), payload)
            .await?
            .event_id,
    )
}

async fn submit_and_settle_control_event(
    client: &TestActorClient,
    realm_id: &str,
    kind: &str,
    payload: Value,
) -> Result<Event> {
    submit_and_settle_control_event_with_preconditions(client, realm_id, kind, payload, Vec::new())
        .await
}

async fn submit_and_settle_control_event_with_preconditions(
    client: &TestActorClient,
    realm_id: &str,
    kind: &str,
    payload: Value,
    preconditions: Vec<Precondition>,
) -> Result<Event> {
    let before = client.realm_seal_frontier(realm_id).await?;
    let before = before["frontier"]["seal_basis"]["leaves"][0]
        .as_str()
        .context("pairwise control transition predecessor Seal")?;
    let event = client
        .author_event_with_preconditions(realm_id, kind, payload, preconditions)
        .await?;
    let response = expect_json(
        client
            .post("/_arkret/self/events")
            .json(&crate::publication::initial_submission(event.clone(), "")?),
        StatusCode::OK,
    )
    .await?;
    let proposal_digest = response["control_proposal_acks"][0]["proposal_digest"]
        .as_str()
        .context("pairwise control transition Control Proposal Ack")?;
    client
        .await_control_proposal_settled(realm_id, proposal_digest, before)
        .await?;
    Ok(event)
}

async fn wait_for_bootstrap_seal(client: &TestActorClient, realm_id: &str) -> Result<()> {
    let deadline = std::time::Instant::now() + Duration::from_secs(45);
    loop {
        match client.realm_seal_frontier(realm_id).await {
            Ok(frontier)
                if frontier["frontier"]["control_event_set_root"].as_str()
                    != Some(
                        "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
                    ) =>
            {
                return Ok(());
            }
            Ok(_) | Err(_) if std::time::Instant::now() < deadline => {
                tokio::time::sleep(Duration::from_millis(100)).await;
            }
            Ok(frontier) => bail!("pairwise Realm bootstrap Seal stayed empty: {frontier}"),
            Err(error) => return Err(error).context("pairwise Realm bootstrap Seal unavailable"),
        }
    }
}

fn governance_binding(
    realm_id: &str,
    mls_group_id: &str,
    previous_epoch: u64,
    next_epoch: u64,
) -> Result<MlsGovernanceBindingPayload> {
    let binding = MlsGovernanceBindingPayload::realm(
        RealmId::new(realm_id.to_owned())?,
        previous_epoch,
        next_epoch,
        Hash::new(format!("sha256:{}", "2".repeat(64)))?,
        ContentScheme::MlsRfc9420,
        None,
        arkret_wire::ProfileId::MLS_GOVERNANCE_BINDING_FULL_V1,
        arkret_wire::CORE_REDUCER_PROFILE,
    )
    .map_err(anyhow::Error::from)?;
    ensure!(
        binding.mls_group_id() == mls_group_id,
        "local MLS group differs from the canonical scope"
    );
    Ok(binding)
}

fn signed_device_claim(
    requester: &ProvisionedTestPrincipal,
    target: &PairwiseKey,
    realm_id: &str,
    mls_group_id: String,
    service_id: &DidCoreId,
    request_label: &str,
    last_resort_allowed: bool,
) -> Result<KeyPackagesClaimRequestBody> {
    let request_token = URL_SAFE_NO_PAD.encode(
        arkret_canonical::canonical::sha256_digest_from_slices(&[
            requester.core_id.as_str().as_bytes(),
            target.actor_id.as_str().as_bytes(),
            realm_id.as_bytes(),
            service_id.as_str().as_bytes(),
            request_label.as_bytes(),
        ])
        .as_bytes(),
    );
    let request_token = request_token.chars().take(32).collect::<String>();
    let signed_at = Utc::now();
    let unsigned = PeerKeyPackagesClaimUnsignedRequest {
        claim_request_id: wire_value(Base64UrlString::new(request_token))?,
        target_account_id: None,
        requester_account_id: Some(AccountId::new(
            requester.core_id.clone(),
            service_id.clone(),
        )),
        intended_realm_id: RealmId::new(realm_id.to_owned())?,
        mls_group_id: wire_value(NonEmptyString::new(mls_group_id))?,
        claim_purpose: PeerKeyPackageClaimPurpose::RealmMembership,
        required_capabilities: ["ak.content.v1", "mimi.content.v1"]
            .into_iter()
            .map(|value| wire_value(NonEmptyString::new(value)))
            .collect::<Result<Vec<_>>>()?,
        expires_at: signed_at + chrono::Duration::minutes(4),
        target_device_ids: Vec::new(),
        target_keypackage_ref: None,
        target_agent_id: None,
        target_agent_verification_method: None,
        target_agent_key_authorize_event_id: None,
        target_pairwise_verification_method: Some(target.verification_method.clone()),
        timeout_ms: Some(30_000),
        strand_id: None,
        pair_key: None,
        last_resort_allowed: Some(last_resort_allowed),
    };
    let service_binding = KeyPackagesClaimServiceBinding {
        source_id: service_id.clone(),
        destination_id: service_id.clone(),
    };
    let verification_method = wire_value(DidUrl::new(format!(
        "{}#{}",
        requester.did, requester.device_id
    )))?;
    let placeholder = KeyOperationSignature {
        kid: wire_value(NonEmptyString::new(verification_method.to_string()))?,
        signature_algorithm: Some(wire_value(NonEmptyString::new("Ed25519"))?),
        sig: wire_value(Base64UrlString::new("AA"))?,
    };
    let mut authorization = PeerKeyPackageRequesterAuthorization::Device {
        verification_method,
        requester_device_id: requester.device_id.clone(),
        device_authorize_event_id: requester.founding_authorize_event_id.clone(),
        signed_at,
        signature: placeholder,
    };
    let signing_bytes =
        keypackage_claim_authorization_signing_bytes(&unsigned, &service_binding, &authorization)?;
    let PeerKeyPackageRequesterAuthorization::Device { signature, .. } = &mut authorization else {
        unreachable!("device claim constructor selected another branch")
    };
    signature.sig = wire_value(Base64UrlString::new(
        URL_SAFE_NO_PAD.encode(requester.device_signing_key.sign(&signing_bytes).to_bytes()),
    ))?;

    let body = KeyPackagesClaimRequestBody {
        claim_request_id: unsigned.claim_request_id,
        target_account_id: unsigned.target_account_id,
        requester_account_id: unsigned.requester_account_id,
        intended_realm_id: unsigned.intended_realm_id,
        mls_group_id: unsigned.mls_group_id,
        claim_purpose: unsigned.claim_purpose,
        required_capabilities: unsigned.required_capabilities,
        expires_at: unsigned.expires_at,
        target_device_ids: unsigned.target_device_ids,
        target_keypackage_ref: unsigned.target_keypackage_ref,
        target_agent_id: unsigned.target_agent_id,
        target_agent_verification_method: unsigned.target_agent_verification_method,
        target_agent_key_authorize_event_id: unsigned.target_agent_key_authorize_event_id,
        target_pairwise_verification_method: unsigned.target_pairwise_verification_method,
        timeout_ms: unsigned.timeout_ms,
        strand_id: unsigned.strand_id,
        pair_key: unsigned.pair_key,
        last_resort_allowed: unsigned.last_resort_allowed,
        service_binding,
        requester_authorization: authorization,
    };
    body.validate_shape()?;
    Ok(body)
}

async fn claim_keypackage(
    client: &TestActorClient,
    claim: &KeyPackagesClaimRequestBody,
) -> Result<KeyPackagesClaimOutcome> {
    let outcome: KeyPackagesClaimOutcome = serde_json::from_value(
        expect_json(client.post(CLAIM_PATH).json(claim), StatusCode::OK).await?,
    )?;
    outcome.validate_shape()?;
    ensure!(outcome.claims.len() == 1, "claim was not a unique CAS");
    Ok(outcome)
}

fn assert_claimed_pairwise_record(
    outcome: &KeyPackagesClaimOutcome,
    target: &PairwiseKey,
    expected: &MlsKeyPackageRecord,
    last_resort: bool,
) -> Result<()> {
    let claimed = &outcome.claims[0];
    ensure!(
        claimed.principal_id == target.actor_id
            && claimed.pairwise_verification_method.as_ref() == Some(&target.verification_method)
            && claimed.device_id.is_none()
            && claimed.agent_id.is_none()
            && claimed.keypackage == expected.keypackage
            && claimed.keypackage_ref == expected.keypackage_ref.as_str()
            && claimed.last_resort == last_resort.then_some(true),
        "claim record did not preserve the expected closed pairwise endpoint and reuse policy"
    );
    Ok(())
}

async fn remove_pairwise_leaf(
    client: &TestActorClient,
    realm_id: &str,
    target: &PairwiseKey,
    requester_group: &mut ArkretMlsGroup,
    base_epoch: u64,
    base_transition: &Event,
) -> Result<Event> {
    let binding = governance_binding(
        realm_id,
        &requester_group.group_id(),
        base_epoch,
        base_epoch + 1,
    )?;
    let removal = requester_group.remove_members_by_actor_with_governance_binding(
        &[arkret_wire::ActorId::service(target.actor_id.clone())],
        &binding,
    )?;
    let commit_payload = MlsCommitPayload::new(
        base_transition.event_id.to_string(),
        Vec::new(),
        &removal.commit,
        binding,
    )?;
    submit_and_settle_control_event_with_preconditions(
        client,
        realm_id,
        EventKind::MlsCommit.as_str(),
        serde_json::to_value(commit_payload)?,
        mls_cas_preconditions(base_transition)?,
    )
    .await
}

#[allow(clippy::too_many_arguments)]
async fn accept_welcome_and_consume(
    client: &TestActorClient,
    realm_id: &str,
    requester: &ProvisionedTestPrincipal,
    target: &PairwiseKey,
    target_identity: ArkretMlsIdentity,
    requester_group: &mut ArkretMlsGroup,
    target_record: &MlsKeyPackageRecord,
    claim_outcome: &KeyPackagesClaimOutcome,
    base_epoch: u64,
    base_transition: &Event,
) -> Result<Event> {
    let claimed = &claim_outcome.claims[0];
    let mut claimed_record = target_record.clone();
    if !claimed_record.last_resort {
        claimed_record.state = arkret::MlsKeyPackageState::Claimed;
        claimed_record.claim_id = Some(claimed.claim_id.clone());
    }
    let binding = governance_binding(
        realm_id,
        &requester_group.group_id(),
        base_epoch,
        base_epoch + 1,
    )?;
    let add = requester_group.add_member_with_governance_binding(&claimed_record, &binding)?;
    ensure!(
        add.welcome.recipient == target_identity.endpoint_identity(),
        "real OpenMLS Welcome recipient differs from the claimed pairwise endpoint"
    );
    let joined = ArkretMlsGroup::join_from_welcome(target_identity, &add.welcome)?;
    ensure!(
        joined.group_id() == requester_group.group_id()
            && joined.epoch() == requester_group.epoch(),
        "target could not cryptographically reconstruct the real RFC 9420 group state"
    );

    let commit_payload = MlsCommitPayload::new(
        base_transition.event_id.to_string(),
        Vec::new(),
        &add.commit,
        binding.clone(),
    )?;
    let commit_event = submit_and_settle_control_event_with_preconditions(
        client,
        realm_id,
        EventKind::MlsCommit.as_str(),
        serde_json::to_value(commit_payload)?,
        mls_cas_preconditions(base_transition)?,
    )
    .await?;

    let keypackage_bytes = arkret_canonical::base64url_decode(claimed.keypackage.as_bytes())?;
    let keypackage_digest = Hash::new(arkret_canonical::sha256_digest(&keypackage_bytes))?;
    let welcome_bytes = arkret_canonical::base64url_decode(add.welcome.welcome.as_bytes())?;
    let welcome_digest = Hash::new(arkret_canonical::sha256_digest(&welcome_bytes))?;
    ensure!(
        welcome_digest == add.welcome.welcome_hash,
        "OpenMLS Welcome digest did not match the decoded RFC 9420 Welcome bytes"
    );
    let capabilities_digest = Hash::new(arkret_canonical::sha256_digest(
        &arkret_canonical::canonical_json_bytes(&claimed.capabilities)?,
    ))?;
    let keypackage_ref = claimed.keypackage_ref.clone();
    let requester_method = wire_value(DidUrl::new(format!(
        "{}#{}",
        requester.did, requester.device_id
    )))?;
    let unsigned_envelope = UnsignedMlsWelcomeClaimEnvelope::new(
        MlsWelcomeClaimEnvelopeSigningInput {
            keypackage_ref: keypackage_ref.clone(),
            keypackage_digest: keypackage_digest.clone(),
            intended_realm_id: RealmId::new(realm_id.to_owned())?,
            claim_id: wire_value(NonEmptyString::new(claimed.claim_id.clone()))?,
            requester_actor_id: ActorId::account(AccountId::new(
                requester.core_id.clone(),
                DidCoreId::new(client.service_id().to_owned())?,
            )),
            trust_binding: MlsRequesterTrustBinding::RequesterDevice {
                requester_device_id: requester.device_id.clone(),
                requester_device_authorize_event_id: requester.founding_authorize_event_id.clone(),
            },
            welcome_digest: welcome_digest.clone(),
            created_at: Utc::now(),
        },
        &claim_outcome.claim_receipt,
    )?;
    let envelope_signature = requester
        .device_signing_key
        .sign(&unsigned_envelope.canonical_signing_bytes()?)
        .to_bytes();
    let claim_envelope: MlsWelcomeClaimEnvelope = unsigned_envelope.attach_signature(
        wire_value(NonEmptyString::new(requester_method.to_string()))?,
        wire_value(Base64UrlString::new(
            URL_SAFE_NO_PAD.encode(envelope_signature),
        ))?,
    )?;
    ensure!(
        binding.mls_group_id() == requester_group.group_id()
            && binding.next_epoch() == add.welcome.epoch,
        "Welcome material differs from its governance binding"
    );
    let welcome_payload = MlsWelcomePayload {
        recipient_principal_id: None,
        recipient: MlsWelcomeRecipient::MinimalMetadataPairwise {
            recipient_pairwise_actor_id: target.actor_id.clone(),
            recipient_pairwise_verification_method: target.verification_method.clone(),
        },
        sender_device_id: Some(requester.device_id.clone()),
        keypackage_ref: keypackage_ref.clone(),
        claim_id: wire_value(NonEmptyString::new(claimed.claim_id.clone()))?,
        claim_ref: MlsWelcomePayloadClaimRef {
            claim_id: wire_value(NonEmptyString::new(claimed.claim_id.clone()))?,
            keypackage_ref,
            keypackage_digest,
            capabilities_digest,
            trust_binding: MlsClaimTrustBinding::MinimalMetadataPairwise {
                pairwise_actor_id: target.actor_id.clone(),
                pairwise_verification_method: target.verification_method.clone(),
            },
        },
        claim_envelope,
        claim_receipt: claim_outcome.claim_receipt.clone(),
        carrier: MlsWelcomeCarrier::new(welcome_bytes).map_err(anyhow::Error::msg)?,
        commit_ref: commit_event.event_id.clone(),
        governance_binding: binding,
        expires_at: claim_outcome.claim_receipt.expires_at,
    };
    let welcome_event = submit_and_settle_control_event(
        client,
        realm_id,
        EventKind::MlsWelcome.as_str(),
        serde_json::to_value(welcome_payload)?,
    )
    .await?;

    let accepted_welcome = expect_json(
        client.get(&format!("/_arkret/self/events/{}", welcome_event.event_id)),
        StatusCode::OK,
    )
    .await?;
    let accepted_welcome: Event = serde_json::from_value(
        accepted_welcome
            .get("event")
            .cloned()
            .context("accepted Welcome resource omitted event")?,
    )?;
    ensure!(
        accepted_welcome.event_id == welcome_event.event_id,
        "accepted Welcome resource returned a different Event"
    );
    let durable_receipt =
        joined
            .identity()
            .sign_recipient_mls_durable_receipt(RecipientMlsDurableReceipt {
                domain: wire_value(NonEmptyString::new(
                    arkret_wire::DomainSeparationId::MLS_RECIPIENT_DURABLE_RECEIPT_V1,
                ))?,
                claim_request_id: claim_outcome.claim_request_id.clone(),
                key_package_ref: wire_value(NonEmptyString::new(claimed.keypackage_ref.clone()))?,
                recipient: RecipientMlsDurableSigner::MinimalMetadataPairwise {
                    recipient_pairwise_verification_method: target.verification_method.clone(),
                },
                recipient_id: DidCoreId::new(client.service_id().to_owned())?,
                realm_id: RealmId::new(realm_id.to_owned())?,
                mls_group_id: wire_value(NonEmptyString::new(requester_group.group_id()))?,
                mls_epoch: add.welcome.epoch,
                welcome_ref: welcome_event.event_id.clone(),
                welcome_digest: welcome_digest.clone(),
                durable_at: Utc::now(),
                signature: target.signature(&[])?,
            })?;
    let consume = joined.identity().signed_key_packages_consume_request(
        wire_value(NonEmptyString::new(claimed.claim_id.clone()))?,
        durable_receipt,
    )?;
    let consume_bytes = arkret_canonical::canonical_json_bytes(&consume)?;
    let first = client
        .post(CONSUME_PATH)
        .header("content-type", "application/json")
        .body(consume_bytes.clone())
        .send()
        .await?;
    let first_status = first.status();
    let first_bytes = first.bytes().await?;
    ensure!(
        first_status == StatusCode::OK,
        "first pairwise consume failed with {first_status}: {}",
        String::from_utf8_lossy(&first_bytes)
    );
    let replay = client
        .post(CONSUME_PATH)
        .header("content-type", "application/json")
        .body(consume_bytes)
        .send()
        .await?;
    let replay_status = replay.status();
    let replay_bytes = replay.bytes().await?;
    ensure!(
        replay_status == StatusCode::OK,
        "pairwise consume replay failed with {replay_status}: {}",
        String::from_utf8_lossy(&replay_bytes)
    );
    ensure!(
        first_bytes == replay_bytes,
        "exact pairwise consume replay did not return byte-identical signed outcome"
    );
    let consume_outcome: KeyPackagesConsumeOutcome = serde_json::from_slice(&first_bytes)?;
    consume_outcome
        .consume_receipt
        .validate_shape()
        .map_err(anyhow::Error::msg)?;
    ensure!(
        consume_outcome.consume_receipt.claim_id.as_str() == claimed.claim_id
            && consume_outcome
                .consume_receipt
                .recipient_durable_receipt
                .welcome_ref
                .as_str()
                == welcome_event.event_id.as_str(),
        "consume outcome drifted from the accepted Welcome and exact claim"
    );
    ensure!(
        consume_outcome
            .consume_receipt
            .recipient_durable_receipt
            .welcome_digest
            == welcome_digest,
        "consume outcome drifted from the decoded RFC 9420 Welcome bytes digest"
    );
    Ok(commit_event)
}

fn mls_cas_preconditions(base_transition: &Event) -> Result<Vec<Precondition>> {
    let preconditions = crate::publication::project_cells(base_transition)
        .map_err(anyhow::Error::msg)?
        .into_iter()
        .filter(|write| {
            write
                .cell_id
                .as_str()
                .starts_with("ak:cell:ak.component.mls.epoch.v1:")
                || write
                    .cell_id
                    .as_str()
                    .starts_with("ak:cell:ak.component.mls.key_schedule.v1:")
        })
        .map(|write| {
            let effect = write
                .as_direct()
                .context("MLS transition cell write unexpectedly requires mutable pre-state")?;
            let value = effect
                .op
                .value
                .context("MLS transition cell write omitted its full register value")?;
            Ok(Precondition {
                cell_id: effect.cell_id,
                predicate: Predicate {
                    op: PredicateOp::HeadEq,
                    value: Some(value),
                    values: None,
                    predicate_id: None,
                },
            })
        })
        .collect::<Result<Vec<_>>>()?;
    ensure!(
        preconditions.len() == 2,
        "MLS transition must guard exactly the epoch and key-schedule CAS cells"
    );
    Ok(preconditions)
}

fn signed_pairwise_claim(
    requester: &PairwiseKey,
    target: &PairwiseKey,
    realm_id: &str,
    mls_group_id: String,
    source_id: DidCoreId,
    destination_id: DidCoreId,
) -> Result<KeyPackagesClaimRequestBody> {
    let request_token = URL_SAFE_NO_PAD.encode(
        arkret_canonical::canonical::sha256_digest_from_slices(&[
            requester.actor_id.as_str().as_bytes(),
            target.actor_id.as_str().as_bytes(),
            realm_id.as_bytes(),
            destination_id.as_str().as_bytes(),
        ])
        .as_bytes(),
    );
    let request_token = request_token.chars().take(32).collect::<String>();
    let signed_at = Utc::now();
    let unsigned = PeerKeyPackagesClaimUnsignedRequest {
        claim_request_id: wire_value(Base64UrlString::new(request_token.clone()))?,
        target_account_id: None,
        requester_account_id: None,
        intended_realm_id: RealmId::new(realm_id.to_owned())?,
        mls_group_id: wire_value(NonEmptyString::new(mls_group_id))?,
        claim_purpose: PeerKeyPackageClaimPurpose::RealmMembership,
        required_capabilities: ["ak.content.v1", "mimi.content.v1"]
            .into_iter()
            .map(|value| wire_value(NonEmptyString::new(value)))
            .collect::<Result<Vec<_>>>()?,
        expires_at: signed_at + chrono::Duration::minutes(4),
        target_device_ids: Vec::new(),
        target_keypackage_ref: None,
        target_agent_id: None,
        target_agent_verification_method: None,
        target_agent_key_authorize_event_id: None,
        target_pairwise_verification_method: Some(target.verification_method.clone()),
        timeout_ms: Some(30_000),
        strand_id: None,
        pair_key: None,
        last_resort_allowed: Some(false),
    };
    let service_binding = KeyPackagesClaimServiceBinding {
        source_id,
        destination_id,
    };
    let mut authorization = PeerKeyPackageRequesterAuthorization::MinimalMetadataPairwise {
        verification_method: requester.verification_method.clone(),
        signed_at,
        // The signature bytes are excluded from the registered transcript.
        // Start with a real Ed25519 signature and replace it with the exact
        // transcript signature immediately below.
        signature: requester.signature(&[])?,
    };
    let signing_bytes =
        keypackage_claim_authorization_signing_bytes(&unsigned, &service_binding, &authorization)?;
    let PeerKeyPackageRequesterAuthorization::MinimalMetadataPairwise { signature, .. } =
        &mut authorization
    else {
        unreachable!("pairwise claim constructor selected another branch")
    };
    *signature = requester.signature(&signing_bytes)?;

    let body = KeyPackagesClaimRequestBody {
        claim_request_id: unsigned.claim_request_id,
        target_account_id: unsigned.target_account_id,
        requester_account_id: unsigned.requester_account_id,
        intended_realm_id: unsigned.intended_realm_id,
        mls_group_id: unsigned.mls_group_id,
        claim_purpose: unsigned.claim_purpose,
        required_capabilities: unsigned.required_capabilities,
        expires_at: unsigned.expires_at,
        target_device_ids: unsigned.target_device_ids,
        target_keypackage_ref: unsigned.target_keypackage_ref,
        target_agent_id: unsigned.target_agent_id,
        target_agent_verification_method: unsigned.target_agent_verification_method,
        target_agent_key_authorize_event_id: unsigned.target_agent_key_authorize_event_id,
        target_pairwise_verification_method: unsigned.target_pairwise_verification_method,
        timeout_ms: unsigned.timeout_ms,
        strand_id: unsigned.strand_id,
        pair_key: unsigned.pair_key,
        last_resort_allowed: unsigned.last_resort_allowed,
        service_binding,
        requester_authorization: authorization,
    };
    body.validate_shape()?;
    Ok(body)
}

async fn reject_upload_mutation(
    client: &TestActorClient,
    upload: &arkret::KeyPackagesUploadRequestBody,
    mutate: impl FnOnce(&mut Value),
) -> Result<()> {
    let mut value = serde_json::to_value(upload)?;
    mutate(&mut value);
    assert_rejected(client.post(UPLOAD_PATH).json(&value).send().await?).await
}

fn signed_pairwise_upload_with_records(
    signer: &PairwiseKey,
    records: &[MlsKeyPackageRecord],
    realm_id: &str,
) -> Result<arkret::KeyPackagesUploadRequestBody> {
    let unsigned = arkret::KeyPackagesUploadUnsignedRequest {
        principal_id: signer.actor_id.clone(),
        device_id: None,
        pairwise_verification_method: Some(signer.verification_method.clone()),
        intended_realm_id: Some(RealmId::new(realm_id.to_owned())?),
        agent_verification_method: None,
        agent_key_authorize_event_id: None,
        keypackages: records
            .iter()
            .map(|record| mls_key_package_record_upload_entry(record).map_err(anyhow::Error::msg))
            .collect::<Result<Vec<_>>>()?,
        expires_at: None,
        strand_id: None,
        mls_group_id: None,
    };
    let signature = signer.signature(&keypackages_upload_signing_input(&unsigned)?)?;
    Ok(unsigned.into_signed(signature))
}

fn signed_ordinary_upload_with_records(
    signer: &ProvisionedTestPrincipal,
    records: &[MlsKeyPackageRecord],
    _realm_id: &str,
) -> Result<arkret::KeyPackagesUploadRequestBody> {
    let unsigned = arkret::KeyPackagesUploadUnsignedRequest {
        principal_id: signer.core_id.clone(),
        device_id: Some(signer.device_id.clone()),
        pairwise_verification_method: None,
        intended_realm_id: None,
        agent_verification_method: None,
        agent_key_authorize_event_id: None,
        keypackages: records
            .iter()
            .map(|record| mls_key_package_record_upload_entry(record).map_err(anyhow::Error::msg))
            .collect::<Result<Vec<_>>>()?,
        expires_at: None,
        strand_id: None,
        mls_group_id: None,
    };
    let signing_bytes = keypackages_upload_signing_input(&unsigned)?;
    let signature = KeyOperationSignature {
        kid: wire_value(NonEmptyString::new(format!(
            "{}#{}",
            signer.did, signer.device_id
        )))?,
        signature_algorithm: Some(wire_value(NonEmptyString::new("Ed25519"))?),
        sig: wire_value(Base64UrlString::new(
            URL_SAFE_NO_PAD.encode(signer.device_signing_key.sign(&signing_bytes).to_bytes()),
        ))?,
    };
    Ok(unsigned.into_signed(signature))
}

async fn assert_upload_entries_rejected(
    client: &TestActorClient,
    upload: &arkret::KeyPackagesUploadRequestBody,
) -> Result<()> {
    let response = client.post(UPLOAD_PATH).json(upload).send().await?;
    if response.status() == StatusCode::OK {
        let outcome: KeyPackagesUploadOutcome = serde_json::from_slice(&response.bytes().await?)?;
        ensure!(
            outcome.accepted == 0 && !outcome.rejections.is_empty(),
            "invalid KeyPackage entry was accepted: {outcome:?}"
        );
        return Ok(());
    }
    assert_rejected(response).await
}

async fn assert_rejected(response: Response) -> Result<()> {
    let status = response.status();
    let body = response.text().await.unwrap_or_default();
    ensure!(
        matches!(
            status,
            StatusCode::BAD_REQUEST
                | StatusCode::FORBIDDEN
                | StatusCode::CONFLICT
                | StatusCode::PRECONDITION_FAILED
                | StatusCode::UNPROCESSABLE_ENTITY
        ),
        "expected a fail-closed protocol rejection, got {status}: {body}"
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pairwise_actor_routes_through_its_host_station() {
        let principal_id = DidCoreId::new("ak:did_core:key:z6Mkfixture").unwrap();
        let station_id = DidCoreId::new("ak:did_core:web:station.example").unwrap();
        let actor = ActorId::account(arkret_wire::AccountId::new(
            principal_id.clone(),
            station_id.clone(),
        ));
        assert_eq!(actor.signing_principal_id(), &principal_id);
        assert_eq!(actor.route_service_id(), &station_id);
    }
}
