param(
    [switch]$Check
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$testsRoot = Join-Path $repoRoot "e2e\tests"
$scenariosRoot = Join-Path $repoRoot "e2e\scenarios"
$catalogPath = Join-Path $scenariosRoot "catalog.md"
$dashboardPath = Join-Path $repoRoot "docs\coverage-dashboard.md"

function Get-RelativeStem {
    param(
        [Parameter(Mandatory)][string]$Root,
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Suffix
    )

    $relative = [IO.Path]::GetRelativePath($Root, $Path) -replace '\\', '/'
    return $relative.Substring(0, $relative.Length - $Suffix.Length)
}

function Get-SpecRows {
    $rows = New-Object System.Collections.Generic.List[object]
    $files = @(Get-ChildItem -LiteralPath $testsRoot -Recurse -File -Filter "*.spec.ts" | Sort-Object FullName)
    foreach ($file in $files) {
        $source = Get-Content -LiteralPath $file.FullName -Raw
        $stem = Get-RelativeStem -Root $testsRoot -Path $file.FullName -Suffix ".spec.ts"
        $domain = ($stem -split '/')[0]

        # Keep these expressions aligned with run-joint-e2e.ps1. A live test is
        # a test(...) definition. Conditional test.skip(...) calls are reported
        # separately and do not turn the definition into a promise placeholder.
        $liveDefinitions = [regex]::Matches($source, '(?m)(^|[^.\w])test\s*\(\s*[''"]').Count
        $skippedDefinitions = [regex]::Matches($source, '(?s)test\.skip\s*\(\s*[''"]').Count
        $live = $liveDefinitions + $skippedDefinitions
        $fixmePattern = '(?s)test\.fixme\s*\(\s*(?:(?://[^\r\n]*(?:\r?\n|\n|\r)\s*)*)(?:"(?:[^"\\]|\\.)*"|''(?:[^''\\]|\\.)*'')'
        $fixme = [regex]::Matches($source, $fixmePattern).Count
        $skip = [regex]::Matches($source, '(?s)test\.skip\s*\(').Count
        $tags = @()
        if ($source -match '@fully-implemented') {
            $tags += '@fully-implemented'
        }

        $rows.Add([pscustomobject]@{
            stem = $stem
            domain = $domain
            live = $live
            fixme = $fixme
            promised = $live + $fixme
            skip = $skip
            tags = $tags
        }) | Out-Null
    }
    return $rows.ToArray()
}

function Get-ScenarioStems {
    $ignored = @('README.md', 'catalog.md', 'user-journeys.md')
    return @(
        Get-ChildItem -LiteralPath $scenariosRoot -Recurse -File -Filter "*.md" |
            Where-Object { $_.Name -notin $ignored } |
            ForEach-Object {
                Get-RelativeStem -Root $scenariosRoot -Path $_.FullName -Suffix ".md"
            } |
            Sort-Object
    )
}

function Get-Ratio {
    param([int]$Verified, [int]$Promised)
    if ($Promised -eq 0) { return '100.0%' }
    return ('{0:P1}' -f ($Verified / $Promised))
}

function Add-Catalog {
    param(
        [Parameter(Mandatory)][object[]]$Rows,
        [Parameter(Mandatory)][string[]]$ScenarioStems
    )

    $scenarioSet = @{}
    foreach ($stem in $ScenarioStems) { $scenarioSet[$stem] = $true }
    $specSet = @{}
    foreach ($row in $Rows) { $specSet[$row.stem] = $true }

    $verified = [int](($Rows.live | Measure-Object -Sum).Sum)
    $fixme = [int](($Rows.fixme | Measure-Object -Sum).Sum)
    $promised = [int](($Rows.promised | Measure-Object -Sum).Sum)
    $skip = [int](($Rows.skip | Measure-Object -Sum).Sum)
    $domains = @($Rows.domain | Sort-Object -Unique)
    $lines = New-Object System.Collections.Generic.List[string]

    $lines.Add('# cotest e2e coverage')
    $lines.Add('')
    $lines.Add("Promised: $promised · Verified: $verified ($(Get-Ratio $verified $promised))")
    $lines.Add('')
    $lines.Add("Totals: $($ScenarioStems.Count) scenarios / $($Rows.Count) specs / $verified verified / $promised promised / $fixme fixme / $skip skip ($($domains.Count) domains)")
    $lines.Add('')
    $lines.Add('Generated by `scripts/generate-e2e-coverage.ps1`; CI may verify it with `-Check`.')
    $lines.Add('')
    $lines.Add('## Totals')
    $lines.Add('')
    $lines.Add('| metric | count |')
    $lines.Add('|---|---:|')
    $lines.Add("| scenario docs | $($ScenarioStems.Count) |")
    $lines.Add("| spec files | $($Rows.Count) |")
    $lines.Add("| live tests | $verified |")
    $lines.Add("| test.fixme | $fixme |")
    $lines.Add("| promised tests | $promised |")
    $lines.Add("| verified tests | $verified |")
    $lines.Add("| verified ratio | $(Get-Ratio $verified $promised) |")
    $lines.Add("| test.skip (conditional) | $skip |")
    $lines.Add("| domains | $($domains.Count) |")
    $lines.Add('')
    $lines.Add('## Per-domain rollup')
    $lines.Add('')
    $lines.Add('| domain | scenarios | specs | verified | promised | ratio | fixme | skip |')
    $lines.Add('|---|---:|---:|---:|---:|---:|---:|---:|')
    foreach ($domain in $domains) {
        $domainRows = @($Rows | Where-Object domain -eq $domain)
        $domainScenarios = @($ScenarioStems | Where-Object { ($_ -split '/')[0] -eq $domain })
        $domainVerified = [int](($domainRows.live | Measure-Object -Sum).Sum)
        $domainPromised = [int](($domainRows.promised | Measure-Object -Sum).Sum)
        $domainFixme = [int](($domainRows.fixme | Measure-Object -Sum).Sum)
        $domainSkip = [int](($domainRows.skip | Measure-Object -Sum).Sum)
        $lines.Add("| $domain | $($domainScenarios.Count) | $($domainRows.Count) | $domainVerified | $domainPromised | $(Get-Ratio $domainVerified $domainPromised) | $domainFixme | $domainSkip |")
    }
    $lines.Add('')
    $lines.Add('## Per-spec')
    $lines.Add('')
    $lines.Add('| spec | verified | promised | ratio | fixme | skip | status | scenario? | tags |')
    $lines.Add('|---|---:|---:|---:|---:|---:|---|---|---|')
    foreach ($row in ($Rows | Sort-Object stem)) {
        $status = if ($row.fixme -eq 0) { 'live-only' } elseif ($row.live -eq 0) { 'fixme-only' } else { 'mixed' }
        $hasScenario = if ($scenarioSet.ContainsKey($row.stem)) { 'yes' } else { 'no' }
        $lines.Add("| $($row.stem) | $($row.live) | $($row.promised) | $(Get-Ratio $row.live $row.promised) | $($row.fixme) | $($row.skip) | $status | $hasScenario | $($row.tags -join ', ') |")
    }
    $lines.Add('')
    $lines.Add('## Orphans')
    $lines.Add('')
    $specsWithoutScenario = @($Rows.stem | Where-Object { -not $scenarioSet.ContainsKey($_) } | Sort-Object)
    $scenariosWithoutSpec = @($ScenarioStems | Where-Object { -not $specSet.ContainsKey($_) } | Sort-Object)
    if ($specsWithoutScenario.Count -eq 0) {
        $lines.Add('- specs without scenario doc: none')
    } else {
        $lines.Add('- specs without scenario doc:')
        foreach ($stem in $specsWithoutScenario) { $lines.Add(('  - `{0}`' -f $stem)) }
    }
    if ($scenariosWithoutSpec.Count -eq 0) {
        $lines.Add('- scenarios without spec file: none')
    } else {
        $lines.Add('- scenarios without spec file:')
        foreach ($stem in $scenariosWithoutSpec) { $lines.Add(('  - `{0}`' -f $stem)) }
    }
    return (($lines -join "`n") + "`n")
}

function Add-Dashboard {
    param([Parameter(Mandatory)][object[]]$Rows)

    $journeys = @(
        [pscustomobject]@{ id = 'UJ-A'; name = 'First login and multi-device recovery'; include = { param($s) $s -like 'identity/*' -or $s -in @('encryption/key-backup', 'encryption/mls-group') } },
        [pscustomobject]@{ id = 'UJ-B'; name = 'Workspace creation, invites, and archive visibility'; include = { param($s) $s -like 'spaces/*' -or $s -like 'invites/*' } },
        [pscustomobject]@{ id = 'UJ-C'; name = 'Daily messaging, edits, reactions, receipts, and mentions'; include = { param($s) $s -like 'messaging/*' -or $s -eq 'discovery/notifications' } },
        [pscustomobject]@{ id = 'UJ-D'; name = 'Encrypted realm lifecycle and cross-device decrypt'; include = { param($s) $s -like 'encryption/*' } },
        [pscustomobject]@{ id = 'UJ-E'; name = 'Federation and cross-domain collaboration'; include = { param($s) $s -like 'federation/*' -or $s -eq 'extensions/mimi-federation' } },
        [pscustomobject]@{ id = 'UJ-F'; name = 'Kanban collaboration and concurrent work'; include = { param($s) $s -like 'kanban/*' -or $s -like 'workflows/*' -or $s -eq 'messaging/discussion-upgrade' } },
        [pscustomobject]@{ id = 'UJ-G'; name = 'Privacy rights, governance, appeal, and GDPR'; include = { param($s) $s -like 'governance/*' -or $s -in @('identity/consent-grant', 'spaces/moderation-ban') } },
        [pscustomobject]@{ id = 'UJ-H'; name = 'Calls, push, and cross-platform sync'; include = { param($s) $s -like 'calls/*' -or $s -in @('discovery/notifications', 'sync/transport-negotiation') } }
    )

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add('# journey coverage')
    $lines.Add('')
    $lines.Add('Generated from `e2e/scenarios/user-journeys.md` by `scripts/generate-e2e-coverage.ps1`.')
    $lines.Add('')
    $lines.Add('| Journey | Verified | Promised | Coverage | Blocking fixme |')
    $lines.Add('|---|---:|---:|---:|---:|')
    $journeyRows = @{}
    foreach ($journey in $journeys) {
        $selected = @($Rows | Where-Object { & $journey.include $_.stem })
        $journeyRows[$journey.id] = $selected
        $verified = [int](($selected.live | Measure-Object -Sum).Sum)
        $promised = [int](($selected.promised | Measure-Object -Sum).Sum)
        $blocking = [int](($selected.fixme | Measure-Object -Sum).Sum)
        $lines.Add("| $($journey.id) - $($journey.name) | $verified | $promised | $(Get-Ratio $verified $promised) | $blocking |")
    }
    foreach ($journey in $journeys) {
        $lines.Add('')
        $lines.Add("## $($journey.id) - $($journey.name)")
        $lines.Add('')
        $lines.Add('| spec | mapping | verified | promised | blocking |')
        $lines.Add('|---|---|---:|---:|---:|')
        foreach ($row in ($journeyRows[$journey.id] | Sort-Object stem)) {
            $lines.Add("| $($row.stem) | domain-fallback | $($row.live) | $($row.promised) | $($row.fixme) |")
        }
    }
    return (($lines -join "`n") + "`n")
}

function Update-GeneratedFile {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Content
    )

    if ($Check) {
        $actual = if (Test-Path -LiteralPath $Path) { (Get-Content -LiteralPath $Path -Raw) -replace "`r`n", "`n" } else { '' }
        if ($actual -ne $Content) {
            throw "generated coverage file is stale: $Path"
        }
        return
    }
    Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8 -NoNewline
}

$rows = @(Get-SpecRows)
$scenarioStems = @(Get-ScenarioStems)
Update-GeneratedFile -Path $catalogPath -Content (Add-Catalog -Rows $rows -ScenarioStems $scenarioStems)
Update-GeneratedFile -Path $dashboardPath -Content (Add-Dashboard -Rows $rows)

if ($Check) {
    Write-Host 'e2e coverage artifacts are current'
} else {
    Write-Host "updated $catalogPath"
    Write-Host "updated $dashboardPath"
}
